package com.changan.mesinterface.model;

import java.util.Date;

public class Degasserdensitydata {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserdensitydata.F_ID
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private Integer fId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserdensitydata.F_LineID
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private String fLineid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserdensitydata.F_StationName
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private String fStationname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserdensitydata.F_MaschinenID
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private String fMaschinenid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserdensitydata.F_DeviceName
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private String fDevicename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserdensitydata.F_Furnace
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private String fFurnace;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserdensitydata.F_RFIDID
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private String fRfidid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserdensitydata.F_Time
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private Date fTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserdensitydata.F_Personnel
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private String fPersonnel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserdensitydata.F_VacuumSample
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private String fVacuumsample;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserdensitydata.F_OrdinarySample
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private String fOrdinarysample;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserdensitydata.F_SampleID
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private String fSampleid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserdensitydata.F_CheckValue
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private String fCheckvalue;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserdensitydata.F_State
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private String fState;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserdensitydata.F_IsSync
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private Integer fIssync;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserdensitydata.EntityId
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private String entityid;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserdensitydata.F_ID
     *
     * @return the value of degasserdensitydata.F_ID
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserdensitydata.F_ID
     *
     * @param fId the value for degasserdensitydata.F_ID
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserdensitydata.F_LineID
     *
     * @return the value of degasserdensitydata.F_LineID
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public String getfLineid() {
        return fLineid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserdensitydata.F_LineID
     *
     * @param fLineid the value for degasserdensitydata.F_LineID
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setfLineid(String fLineid) {
        this.fLineid = fLineid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserdensitydata.F_StationName
     *
     * @return the value of degasserdensitydata.F_StationName
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public String getfStationname() {
        return fStationname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserdensitydata.F_StationName
     *
     * @param fStationname the value for degasserdensitydata.F_StationName
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setfStationname(String fStationname) {
        this.fStationname = fStationname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserdensitydata.F_MaschinenID
     *
     * @return the value of degasserdensitydata.F_MaschinenID
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public String getfMaschinenid() {
        return fMaschinenid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserdensitydata.F_MaschinenID
     *
     * @param fMaschinenid the value for degasserdensitydata.F_MaschinenID
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setfMaschinenid(String fMaschinenid) {
        this.fMaschinenid = fMaschinenid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserdensitydata.F_DeviceName
     *
     * @return the value of degasserdensitydata.F_DeviceName
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public String getfDevicename() {
        return fDevicename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserdensitydata.F_DeviceName
     *
     * @param fDevicename the value for degasserdensitydata.F_DeviceName
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setfDevicename(String fDevicename) {
        this.fDevicename = fDevicename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserdensitydata.F_Furnace
     *
     * @return the value of degasserdensitydata.F_Furnace
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public String getfFurnace() {
        return fFurnace;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserdensitydata.F_Furnace
     *
     * @param fFurnace the value for degasserdensitydata.F_Furnace
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setfFurnace(String fFurnace) {
        this.fFurnace = fFurnace;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserdensitydata.F_RFIDID
     *
     * @return the value of degasserdensitydata.F_RFIDID
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public String getfRfidid() {
        return fRfidid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserdensitydata.F_RFIDID
     *
     * @param fRfidid the value for degasserdensitydata.F_RFIDID
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setfRfidid(String fRfidid) {
        this.fRfidid = fRfidid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserdensitydata.F_Time
     *
     * @return the value of degasserdensitydata.F_Time
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public Date getfTime() {
        return fTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserdensitydata.F_Time
     *
     * @param fTime the value for degasserdensitydata.F_Time
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setfTime(Date fTime) {
        this.fTime = fTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserdensitydata.F_Personnel
     *
     * @return the value of degasserdensitydata.F_Personnel
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public String getfPersonnel() {
        return fPersonnel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserdensitydata.F_Personnel
     *
     * @param fPersonnel the value for degasserdensitydata.F_Personnel
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setfPersonnel(String fPersonnel) {
        this.fPersonnel = fPersonnel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserdensitydata.F_VacuumSample
     *
     * @return the value of degasserdensitydata.F_VacuumSample
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public String getfVacuumsample() {
        return fVacuumsample;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserdensitydata.F_VacuumSample
     *
     * @param fVacuumsample the value for degasserdensitydata.F_VacuumSample
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setfVacuumsample(String fVacuumsample) {
        this.fVacuumsample = fVacuumsample;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserdensitydata.F_OrdinarySample
     *
     * @return the value of degasserdensitydata.F_OrdinarySample
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public String getfOrdinarysample() {
        return fOrdinarysample;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserdensitydata.F_OrdinarySample
     *
     * @param fOrdinarysample the value for degasserdensitydata.F_OrdinarySample
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setfOrdinarysample(String fOrdinarysample) {
        this.fOrdinarysample = fOrdinarysample;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserdensitydata.F_SampleID
     *
     * @return the value of degasserdensitydata.F_SampleID
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public String getfSampleid() {
        return fSampleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserdensitydata.F_SampleID
     *
     * @param fSampleid the value for degasserdensitydata.F_SampleID
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setfSampleid(String fSampleid) {
        this.fSampleid = fSampleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserdensitydata.F_CheckValue
     *
     * @return the value of degasserdensitydata.F_CheckValue
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public String getfCheckvalue() {
        return fCheckvalue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserdensitydata.F_CheckValue
     *
     * @param fCheckvalue the value for degasserdensitydata.F_CheckValue
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setfCheckvalue(String fCheckvalue) {
        this.fCheckvalue = fCheckvalue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserdensitydata.F_State
     *
     * @return the value of degasserdensitydata.F_State
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public String getfState() {
        return fState;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserdensitydata.F_State
     *
     * @param fState the value for degasserdensitydata.F_State
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setfState(String fState) {
        this.fState = fState;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserdensitydata.F_IsSync
     *
     * @return the value of degasserdensitydata.F_IsSync
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public Integer getfIssync() {
        return fIssync;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserdensitydata.F_IsSync
     *
     * @param fIssync the value for degasserdensitydata.F_IsSync
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setfIssync(Integer fIssync) {
        this.fIssync = fIssync;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserdensitydata.EntityId
     *
     * @return the value of degasserdensitydata.EntityId
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public String getEntityid() {
        return entityid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserdensitydata.EntityId
     *
     * @param entityid the value for degasserdensitydata.EntityId
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setEntityid(String entityid) {
        this.entityid = entityid;
    }
}