package com.changan.mesinterface.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DegasserdensitydataExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public DegasserdensitydataExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    protected DegasserdensitydataExample(DegasserdensitydataExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andFIdIsNull() {
            addCriterion("F_ID is null");
            return this;
        }

        public Criteria andFIdIsNotNull() {
            addCriterion("F_ID is not null");
            return this;
        }

        public Criteria andFIdEqualTo(Integer value) {
            addCriterion("F_ID =", value, "fId");
            return this;
        }

        public Criteria andFIdNotEqualTo(Integer value) {
            addCriterion("F_ID <>", value, "fId");
            return this;
        }

        public Criteria andFIdGreaterThan(Integer value) {
            addCriterion("F_ID >", value, "fId");
            return this;
        }

        public Criteria andFIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("F_ID >=", value, "fId");
            return this;
        }

        public Criteria andFIdLessThan(Integer value) {
            addCriterion("F_ID <", value, "fId");
            return this;
        }

        public Criteria andFIdLessThanOrEqualTo(Integer value) {
            addCriterion("F_ID <=", value, "fId");
            return this;
        }

        public Criteria andFIdIn(List values) {
            addCriterion("F_ID in", values, "fId");
            return this;
        }

        public Criteria andFIdNotIn(List values) {
            addCriterion("F_ID not in", values, "fId");
            return this;
        }

        public Criteria andFIdBetween(Integer value1, Integer value2) {
            addCriterion("F_ID between", value1, value2, "fId");
            return this;
        }

        public Criteria andFIdNotBetween(Integer value1, Integer value2) {
            addCriterion("F_ID not between", value1, value2, "fId");
            return this;
        }

        public Criteria andFLineidIsNull() {
            addCriterion("F_LineID is null");
            return this;
        }

        public Criteria andFLineidIsNotNull() {
            addCriterion("F_LineID is not null");
            return this;
        }

        public Criteria andFLineidEqualTo(String value) {
            addCriterion("F_LineID =", value, "fLineid");
            return this;
        }

        public Criteria andFLineidNotEqualTo(String value) {
            addCriterion("F_LineID <>", value, "fLineid");
            return this;
        }

        public Criteria andFLineidGreaterThan(String value) {
            addCriterion("F_LineID >", value, "fLineid");
            return this;
        }

        public Criteria andFLineidGreaterThanOrEqualTo(String value) {
            addCriterion("F_LineID >=", value, "fLineid");
            return this;
        }

        public Criteria andFLineidLessThan(String value) {
            addCriterion("F_LineID <", value, "fLineid");
            return this;
        }

        public Criteria andFLineidLessThanOrEqualTo(String value) {
            addCriterion("F_LineID <=", value, "fLineid");
            return this;
        }

        public Criteria andFLineidLike(String value) {
            addCriterion("F_LineID like", value, "fLineid");
            return this;
        }

        public Criteria andFLineidNotLike(String value) {
            addCriterion("F_LineID not like", value, "fLineid");
            return this;
        }

        public Criteria andFLineidIn(List values) {
            addCriterion("F_LineID in", values, "fLineid");
            return this;
        }

        public Criteria andFLineidNotIn(List values) {
            addCriterion("F_LineID not in", values, "fLineid");
            return this;
        }

        public Criteria andFLineidBetween(String value1, String value2) {
            addCriterion("F_LineID between", value1, value2, "fLineid");
            return this;
        }

        public Criteria andFLineidNotBetween(String value1, String value2) {
            addCriterion("F_LineID not between", value1, value2, "fLineid");
            return this;
        }

        public Criteria andFStationnameIsNull() {
            addCriterion("F_StationName is null");
            return this;
        }

        public Criteria andFStationnameIsNotNull() {
            addCriterion("F_StationName is not null");
            return this;
        }

        public Criteria andFStationnameEqualTo(String value) {
            addCriterion("F_StationName =", value, "fStationname");
            return this;
        }

        public Criteria andFStationnameNotEqualTo(String value) {
            addCriterion("F_StationName <>", value, "fStationname");
            return this;
        }

        public Criteria andFStationnameGreaterThan(String value) {
            addCriterion("F_StationName >", value, "fStationname");
            return this;
        }

        public Criteria andFStationnameGreaterThanOrEqualTo(String value) {
            addCriterion("F_StationName >=", value, "fStationname");
            return this;
        }

        public Criteria andFStationnameLessThan(String value) {
            addCriterion("F_StationName <", value, "fStationname");
            return this;
        }

        public Criteria andFStationnameLessThanOrEqualTo(String value) {
            addCriterion("F_StationName <=", value, "fStationname");
            return this;
        }

        public Criteria andFStationnameLike(String value) {
            addCriterion("F_StationName like", value, "fStationname");
            return this;
        }

        public Criteria andFStationnameNotLike(String value) {
            addCriterion("F_StationName not like", value, "fStationname");
            return this;
        }

        public Criteria andFStationnameIn(List values) {
            addCriterion("F_StationName in", values, "fStationname");
            return this;
        }

        public Criteria andFStationnameNotIn(List values) {
            addCriterion("F_StationName not in", values, "fStationname");
            return this;
        }

        public Criteria andFStationnameBetween(String value1, String value2) {
            addCriterion("F_StationName between", value1, value2, "fStationname");
            return this;
        }

        public Criteria andFStationnameNotBetween(String value1, String value2) {
            addCriterion("F_StationName not between", value1, value2, "fStationname");
            return this;
        }

        public Criteria andFMaschinenidIsNull() {
            addCriterion("F_MaschinenID is null");
            return this;
        }

        public Criteria andFMaschinenidIsNotNull() {
            addCriterion("F_MaschinenID is not null");
            return this;
        }

        public Criteria andFMaschinenidEqualTo(String value) {
            addCriterion("F_MaschinenID =", value, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidNotEqualTo(String value) {
            addCriterion("F_MaschinenID <>", value, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidGreaterThan(String value) {
            addCriterion("F_MaschinenID >", value, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidGreaterThanOrEqualTo(String value) {
            addCriterion("F_MaschinenID >=", value, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidLessThan(String value) {
            addCriterion("F_MaschinenID <", value, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidLessThanOrEqualTo(String value) {
            addCriterion("F_MaschinenID <=", value, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidLike(String value) {
            addCriterion("F_MaschinenID like", value, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidNotLike(String value) {
            addCriterion("F_MaschinenID not like", value, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidIn(List values) {
            addCriterion("F_MaschinenID in", values, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidNotIn(List values) {
            addCriterion("F_MaschinenID not in", values, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidBetween(String value1, String value2) {
            addCriterion("F_MaschinenID between", value1, value2, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidNotBetween(String value1, String value2) {
            addCriterion("F_MaschinenID not between", value1, value2, "fMaschinenid");
            return this;
        }

        public Criteria andFDevicenameIsNull() {
            addCriterion("F_DeviceName is null");
            return this;
        }

        public Criteria andFDevicenameIsNotNull() {
            addCriterion("F_DeviceName is not null");
            return this;
        }

        public Criteria andFDevicenameEqualTo(String value) {
            addCriterion("F_DeviceName =", value, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameNotEqualTo(String value) {
            addCriterion("F_DeviceName <>", value, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameGreaterThan(String value) {
            addCriterion("F_DeviceName >", value, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameGreaterThanOrEqualTo(String value) {
            addCriterion("F_DeviceName >=", value, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameLessThan(String value) {
            addCriterion("F_DeviceName <", value, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameLessThanOrEqualTo(String value) {
            addCriterion("F_DeviceName <=", value, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameLike(String value) {
            addCriterion("F_DeviceName like", value, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameNotLike(String value) {
            addCriterion("F_DeviceName not like", value, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameIn(List values) {
            addCriterion("F_DeviceName in", values, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameNotIn(List values) {
            addCriterion("F_DeviceName not in", values, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameBetween(String value1, String value2) {
            addCriterion("F_DeviceName between", value1, value2, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameNotBetween(String value1, String value2) {
            addCriterion("F_DeviceName not between", value1, value2, "fDevicename");
            return this;
        }

        public Criteria andFFurnaceIsNull() {
            addCriterion("F_Furnace is null");
            return this;
        }

        public Criteria andFFurnaceIsNotNull() {
            addCriterion("F_Furnace is not null");
            return this;
        }

        public Criteria andFFurnaceEqualTo(String value) {
            addCriterion("F_Furnace =", value, "fFurnace");
            return this;
        }

        public Criteria andFFurnaceNotEqualTo(String value) {
            addCriterion("F_Furnace <>", value, "fFurnace");
            return this;
        }

        public Criteria andFFurnaceGreaterThan(String value) {
            addCriterion("F_Furnace >", value, "fFurnace");
            return this;
        }

        public Criteria andFFurnaceGreaterThanOrEqualTo(String value) {
            addCriterion("F_Furnace >=", value, "fFurnace");
            return this;
        }

        public Criteria andFFurnaceLessThan(String value) {
            addCriterion("F_Furnace <", value, "fFurnace");
            return this;
        }

        public Criteria andFFurnaceLessThanOrEqualTo(String value) {
            addCriterion("F_Furnace <=", value, "fFurnace");
            return this;
        }

        public Criteria andFFurnaceLike(String value) {
            addCriterion("F_Furnace like", value, "fFurnace");
            return this;
        }

        public Criteria andFFurnaceNotLike(String value) {
            addCriterion("F_Furnace not like", value, "fFurnace");
            return this;
        }

        public Criteria andFFurnaceIn(List values) {
            addCriterion("F_Furnace in", values, "fFurnace");
            return this;
        }

        public Criteria andFFurnaceNotIn(List values) {
            addCriterion("F_Furnace not in", values, "fFurnace");
            return this;
        }

        public Criteria andFFurnaceBetween(String value1, String value2) {
            addCriterion("F_Furnace between", value1, value2, "fFurnace");
            return this;
        }

        public Criteria andFFurnaceNotBetween(String value1, String value2) {
            addCriterion("F_Furnace not between", value1, value2, "fFurnace");
            return this;
        }

        public Criteria andFRfididIsNull() {
            addCriterion("F_RFIDID is null");
            return this;
        }

        public Criteria andFRfididIsNotNull() {
            addCriterion("F_RFIDID is not null");
            return this;
        }

        public Criteria andFRfididEqualTo(String value) {
            addCriterion("F_RFIDID =", value, "fRfidid");
            return this;
        }

        public Criteria andFRfididNotEqualTo(String value) {
            addCriterion("F_RFIDID <>", value, "fRfidid");
            return this;
        }

        public Criteria andFRfididGreaterThan(String value) {
            addCriterion("F_RFIDID >", value, "fRfidid");
            return this;
        }

        public Criteria andFRfididGreaterThanOrEqualTo(String value) {
            addCriterion("F_RFIDID >=", value, "fRfidid");
            return this;
        }

        public Criteria andFRfididLessThan(String value) {
            addCriterion("F_RFIDID <", value, "fRfidid");
            return this;
        }

        public Criteria andFRfididLessThanOrEqualTo(String value) {
            addCriterion("F_RFIDID <=", value, "fRfidid");
            return this;
        }

        public Criteria andFRfididLike(String value) {
            addCriterion("F_RFIDID like", value, "fRfidid");
            return this;
        }

        public Criteria andFRfididNotLike(String value) {
            addCriterion("F_RFIDID not like", value, "fRfidid");
            return this;
        }

        public Criteria andFRfididIn(List values) {
            addCriterion("F_RFIDID in", values, "fRfidid");
            return this;
        }

        public Criteria andFRfididNotIn(List values) {
            addCriterion("F_RFIDID not in", values, "fRfidid");
            return this;
        }

        public Criteria andFRfididBetween(String value1, String value2) {
            addCriterion("F_RFIDID between", value1, value2, "fRfidid");
            return this;
        }

        public Criteria andFRfididNotBetween(String value1, String value2) {
            addCriterion("F_RFIDID not between", value1, value2, "fRfidid");
            return this;
        }

        public Criteria andFTimeIsNull() {
            addCriterion("F_Time is null");
            return this;
        }

        public Criteria andFTimeIsNotNull() {
            addCriterion("F_Time is not null");
            return this;
        }

        public Criteria andFTimeEqualTo(Date value) {
            addCriterion("F_Time =", value, "fTime");
            return this;
        }

        public Criteria andFTimeNotEqualTo(Date value) {
            addCriterion("F_Time <>", value, "fTime");
            return this;
        }

        public Criteria andFTimeGreaterThan(Date value) {
            addCriterion("F_Time >", value, "fTime");
            return this;
        }

        public Criteria andFTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("F_Time >=", value, "fTime");
            return this;
        }

        public Criteria andFTimeLessThan(Date value) {
            addCriterion("F_Time <", value, "fTime");
            return this;
        }

        public Criteria andFTimeLessThanOrEqualTo(Date value) {
            addCriterion("F_Time <=", value, "fTime");
            return this;
        }

        public Criteria andFTimeIn(List values) {
            addCriterion("F_Time in", values, "fTime");
            return this;
        }

        public Criteria andFTimeNotIn(List values) {
            addCriterion("F_Time not in", values, "fTime");
            return this;
        }

        public Criteria andFTimeBetween(Date value1, Date value2) {
            addCriterion("F_Time between", value1, value2, "fTime");
            return this;
        }

        public Criteria andFTimeNotBetween(Date value1, Date value2) {
            addCriterion("F_Time not between", value1, value2, "fTime");
            return this;
        }

        public Criteria andFPersonnelIsNull() {
            addCriterion("F_Personnel is null");
            return this;
        }

        public Criteria andFPersonnelIsNotNull() {
            addCriterion("F_Personnel is not null");
            return this;
        }

        public Criteria andFPersonnelEqualTo(String value) {
            addCriterion("F_Personnel =", value, "fPersonnel");
            return this;
        }

        public Criteria andFPersonnelNotEqualTo(String value) {
            addCriterion("F_Personnel <>", value, "fPersonnel");
            return this;
        }

        public Criteria andFPersonnelGreaterThan(String value) {
            addCriterion("F_Personnel >", value, "fPersonnel");
            return this;
        }

        public Criteria andFPersonnelGreaterThanOrEqualTo(String value) {
            addCriterion("F_Personnel >=", value, "fPersonnel");
            return this;
        }

        public Criteria andFPersonnelLessThan(String value) {
            addCriterion("F_Personnel <", value, "fPersonnel");
            return this;
        }

        public Criteria andFPersonnelLessThanOrEqualTo(String value) {
            addCriterion("F_Personnel <=", value, "fPersonnel");
            return this;
        }

        public Criteria andFPersonnelLike(String value) {
            addCriterion("F_Personnel like", value, "fPersonnel");
            return this;
        }

        public Criteria andFPersonnelNotLike(String value) {
            addCriterion("F_Personnel not like", value, "fPersonnel");
            return this;
        }

        public Criteria andFPersonnelIn(List values) {
            addCriterion("F_Personnel in", values, "fPersonnel");
            return this;
        }

        public Criteria andFPersonnelNotIn(List values) {
            addCriterion("F_Personnel not in", values, "fPersonnel");
            return this;
        }

        public Criteria andFPersonnelBetween(String value1, String value2) {
            addCriterion("F_Personnel between", value1, value2, "fPersonnel");
            return this;
        }

        public Criteria andFPersonnelNotBetween(String value1, String value2) {
            addCriterion("F_Personnel not between", value1, value2, "fPersonnel");
            return this;
        }

        public Criteria andFVacuumsampleIsNull() {
            addCriterion("F_VacuumSample is null");
            return this;
        }

        public Criteria andFVacuumsampleIsNotNull() {
            addCriterion("F_VacuumSample is not null");
            return this;
        }

        public Criteria andFVacuumsampleEqualTo(String value) {
            addCriterion("F_VacuumSample =", value, "fVacuumsample");
            return this;
        }

        public Criteria andFVacuumsampleNotEqualTo(String value) {
            addCriterion("F_VacuumSample <>", value, "fVacuumsample");
            return this;
        }

        public Criteria andFVacuumsampleGreaterThan(String value) {
            addCriterion("F_VacuumSample >", value, "fVacuumsample");
            return this;
        }

        public Criteria andFVacuumsampleGreaterThanOrEqualTo(String value) {
            addCriterion("F_VacuumSample >=", value, "fVacuumsample");
            return this;
        }

        public Criteria andFVacuumsampleLessThan(String value) {
            addCriterion("F_VacuumSample <", value, "fVacuumsample");
            return this;
        }

        public Criteria andFVacuumsampleLessThanOrEqualTo(String value) {
            addCriterion("F_VacuumSample <=", value, "fVacuumsample");
            return this;
        }

        public Criteria andFVacuumsampleLike(String value) {
            addCriterion("F_VacuumSample like", value, "fVacuumsample");
            return this;
        }

        public Criteria andFVacuumsampleNotLike(String value) {
            addCriterion("F_VacuumSample not like", value, "fVacuumsample");
            return this;
        }

        public Criteria andFVacuumsampleIn(List values) {
            addCriterion("F_VacuumSample in", values, "fVacuumsample");
            return this;
        }

        public Criteria andFVacuumsampleNotIn(List values) {
            addCriterion("F_VacuumSample not in", values, "fVacuumsample");
            return this;
        }

        public Criteria andFVacuumsampleBetween(String value1, String value2) {
            addCriterion("F_VacuumSample between", value1, value2, "fVacuumsample");
            return this;
        }

        public Criteria andFVacuumsampleNotBetween(String value1, String value2) {
            addCriterion("F_VacuumSample not between", value1, value2, "fVacuumsample");
            return this;
        }

        public Criteria andFOrdinarysampleIsNull() {
            addCriterion("F_OrdinarySample is null");
            return this;
        }

        public Criteria andFOrdinarysampleIsNotNull() {
            addCriterion("F_OrdinarySample is not null");
            return this;
        }

        public Criteria andFOrdinarysampleEqualTo(String value) {
            addCriterion("F_OrdinarySample =", value, "fOrdinarysample");
            return this;
        }

        public Criteria andFOrdinarysampleNotEqualTo(String value) {
            addCriterion("F_OrdinarySample <>", value, "fOrdinarysample");
            return this;
        }

        public Criteria andFOrdinarysampleGreaterThan(String value) {
            addCriterion("F_OrdinarySample >", value, "fOrdinarysample");
            return this;
        }

        public Criteria andFOrdinarysampleGreaterThanOrEqualTo(String value) {
            addCriterion("F_OrdinarySample >=", value, "fOrdinarysample");
            return this;
        }

        public Criteria andFOrdinarysampleLessThan(String value) {
            addCriterion("F_OrdinarySample <", value, "fOrdinarysample");
            return this;
        }

        public Criteria andFOrdinarysampleLessThanOrEqualTo(String value) {
            addCriterion("F_OrdinarySample <=", value, "fOrdinarysample");
            return this;
        }

        public Criteria andFOrdinarysampleLike(String value) {
            addCriterion("F_OrdinarySample like", value, "fOrdinarysample");
            return this;
        }

        public Criteria andFOrdinarysampleNotLike(String value) {
            addCriterion("F_OrdinarySample not like", value, "fOrdinarysample");
            return this;
        }

        public Criteria andFOrdinarysampleIn(List values) {
            addCriterion("F_OrdinarySample in", values, "fOrdinarysample");
            return this;
        }

        public Criteria andFOrdinarysampleNotIn(List values) {
            addCriterion("F_OrdinarySample not in", values, "fOrdinarysample");
            return this;
        }

        public Criteria andFOrdinarysampleBetween(String value1, String value2) {
            addCriterion("F_OrdinarySample between", value1, value2, "fOrdinarysample");
            return this;
        }

        public Criteria andFOrdinarysampleNotBetween(String value1, String value2) {
            addCriterion("F_OrdinarySample not between", value1, value2, "fOrdinarysample");
            return this;
        }

        public Criteria andFSampleidIsNull() {
            addCriterion("F_SampleID is null");
            return this;
        }

        public Criteria andFSampleidIsNotNull() {
            addCriterion("F_SampleID is not null");
            return this;
        }

        public Criteria andFSampleidEqualTo(String value) {
            addCriterion("F_SampleID =", value, "fSampleid");
            return this;
        }

        public Criteria andFSampleidNotEqualTo(String value) {
            addCriterion("F_SampleID <>", value, "fSampleid");
            return this;
        }

        public Criteria andFSampleidGreaterThan(String value) {
            addCriterion("F_SampleID >", value, "fSampleid");
            return this;
        }

        public Criteria andFSampleidGreaterThanOrEqualTo(String value) {
            addCriterion("F_SampleID >=", value, "fSampleid");
            return this;
        }

        public Criteria andFSampleidLessThan(String value) {
            addCriterion("F_SampleID <", value, "fSampleid");
            return this;
        }

        public Criteria andFSampleidLessThanOrEqualTo(String value) {
            addCriterion("F_SampleID <=", value, "fSampleid");
            return this;
        }

        public Criteria andFSampleidLike(String value) {
            addCriterion("F_SampleID like", value, "fSampleid");
            return this;
        }

        public Criteria andFSampleidNotLike(String value) {
            addCriterion("F_SampleID not like", value, "fSampleid");
            return this;
        }

        public Criteria andFSampleidIn(List values) {
            addCriterion("F_SampleID in", values, "fSampleid");
            return this;
        }

        public Criteria andFSampleidNotIn(List values) {
            addCriterion("F_SampleID not in", values, "fSampleid");
            return this;
        }

        public Criteria andFSampleidBetween(String value1, String value2) {
            addCriterion("F_SampleID between", value1, value2, "fSampleid");
            return this;
        }

        public Criteria andFSampleidNotBetween(String value1, String value2) {
            addCriterion("F_SampleID not between", value1, value2, "fSampleid");
            return this;
        }

        public Criteria andFCheckvalueIsNull() {
            addCriterion("F_CheckValue is null");
            return this;
        }

        public Criteria andFCheckvalueIsNotNull() {
            addCriterion("F_CheckValue is not null");
            return this;
        }

        public Criteria andFCheckvalueEqualTo(String value) {
            addCriterion("F_CheckValue =", value, "fCheckvalue");
            return this;
        }

        public Criteria andFCheckvalueNotEqualTo(String value) {
            addCriterion("F_CheckValue <>", value, "fCheckvalue");
            return this;
        }

        public Criteria andFCheckvalueGreaterThan(String value) {
            addCriterion("F_CheckValue >", value, "fCheckvalue");
            return this;
        }

        public Criteria andFCheckvalueGreaterThanOrEqualTo(String value) {
            addCriterion("F_CheckValue >=", value, "fCheckvalue");
            return this;
        }

        public Criteria andFCheckvalueLessThan(String value) {
            addCriterion("F_CheckValue <", value, "fCheckvalue");
            return this;
        }

        public Criteria andFCheckvalueLessThanOrEqualTo(String value) {
            addCriterion("F_CheckValue <=", value, "fCheckvalue");
            return this;
        }

        public Criteria andFCheckvalueLike(String value) {
            addCriterion("F_CheckValue like", value, "fCheckvalue");
            return this;
        }

        public Criteria andFCheckvalueNotLike(String value) {
            addCriterion("F_CheckValue not like", value, "fCheckvalue");
            return this;
        }

        public Criteria andFCheckvalueIn(List values) {
            addCriterion("F_CheckValue in", values, "fCheckvalue");
            return this;
        }

        public Criteria andFCheckvalueNotIn(List values) {
            addCriterion("F_CheckValue not in", values, "fCheckvalue");
            return this;
        }

        public Criteria andFCheckvalueBetween(String value1, String value2) {
            addCriterion("F_CheckValue between", value1, value2, "fCheckvalue");
            return this;
        }

        public Criteria andFCheckvalueNotBetween(String value1, String value2) {
            addCriterion("F_CheckValue not between", value1, value2, "fCheckvalue");
            return this;
        }

        public Criteria andFStateIsNull() {
            addCriterion("F_State is null");
            return this;
        }

        public Criteria andFStateIsNotNull() {
            addCriterion("F_State is not null");
            return this;
        }

        public Criteria andFStateEqualTo(String value) {
            addCriterion("F_State =", value, "fState");
            return this;
        }

        public Criteria andFStateNotEqualTo(String value) {
            addCriterion("F_State <>", value, "fState");
            return this;
        }

        public Criteria andFStateGreaterThan(String value) {
            addCriterion("F_State >", value, "fState");
            return this;
        }

        public Criteria andFStateGreaterThanOrEqualTo(String value) {
            addCriterion("F_State >=", value, "fState");
            return this;
        }

        public Criteria andFStateLessThan(String value) {
            addCriterion("F_State <", value, "fState");
            return this;
        }

        public Criteria andFStateLessThanOrEqualTo(String value) {
            addCriterion("F_State <=", value, "fState");
            return this;
        }

        public Criteria andFStateLike(String value) {
            addCriterion("F_State like", value, "fState");
            return this;
        }

        public Criteria andFStateNotLike(String value) {
            addCriterion("F_State not like", value, "fState");
            return this;
        }

        public Criteria andFStateIn(List values) {
            addCriterion("F_State in", values, "fState");
            return this;
        }

        public Criteria andFStateNotIn(List values) {
            addCriterion("F_State not in", values, "fState");
            return this;
        }

        public Criteria andFStateBetween(String value1, String value2) {
            addCriterion("F_State between", value1, value2, "fState");
            return this;
        }

        public Criteria andFStateNotBetween(String value1, String value2) {
            addCriterion("F_State not between", value1, value2, "fState");
            return this;
        }

        public Criteria andFIssyncIsNull() {
            addCriterion("F_IsSync is null");
            return this;
        }

        public Criteria andFIssyncIsNotNull() {
            addCriterion("F_IsSync is not null");
            return this;
        }

        public Criteria andFIssyncEqualTo(Integer value) {
            addCriterion("F_IsSync =", value, "fIssync");
            return this;
        }

        public Criteria andFIssyncNotEqualTo(Integer value) {
            addCriterion("F_IsSync <>", value, "fIssync");
            return this;
        }

        public Criteria andFIssyncGreaterThan(Integer value) {
            addCriterion("F_IsSync >", value, "fIssync");
            return this;
        }

        public Criteria andFIssyncGreaterThanOrEqualTo(Integer value) {
            addCriterion("F_IsSync >=", value, "fIssync");
            return this;
        }

        public Criteria andFIssyncLessThan(Integer value) {
            addCriterion("F_IsSync <", value, "fIssync");
            return this;
        }

        public Criteria andFIssyncLessThanOrEqualTo(Integer value) {
            addCriterion("F_IsSync <=", value, "fIssync");
            return this;
        }

        public Criteria andFIssyncIn(List values) {
            addCriterion("F_IsSync in", values, "fIssync");
            return this;
        }

        public Criteria andFIssyncNotIn(List values) {
            addCriterion("F_IsSync not in", values, "fIssync");
            return this;
        }

        public Criteria andFIssyncBetween(Integer value1, Integer value2) {
            addCriterion("F_IsSync between", value1, value2, "fIssync");
            return this;
        }

        public Criteria andFIssyncNotBetween(Integer value1, Integer value2) {
            addCriterion("F_IsSync not between", value1, value2, "fIssync");
            return this;
        }

        public Criteria andEntityidIsNull() {
            addCriterion("EntityId is null");
            return this;
        }

        public Criteria andEntityidIsNotNull() {
            addCriterion("EntityId is not null");
            return this;
        }

        public Criteria andEntityidEqualTo(String value) {
            addCriterion("EntityId =", value, "entityid");
            return this;
        }

        public Criteria andEntityidNotEqualTo(String value) {
            addCriterion("EntityId <>", value, "entityid");
            return this;
        }

        public Criteria andEntityidGreaterThan(String value) {
            addCriterion("EntityId >", value, "entityid");
            return this;
        }

        public Criteria andEntityidGreaterThanOrEqualTo(String value) {
            addCriterion("EntityId >=", value, "entityid");
            return this;
        }

        public Criteria andEntityidLessThan(String value) {
            addCriterion("EntityId <", value, "entityid");
            return this;
        }

        public Criteria andEntityidLessThanOrEqualTo(String value) {
            addCriterion("EntityId <=", value, "entityid");
            return this;
        }

        public Criteria andEntityidLike(String value) {
            addCriterion("EntityId like", value, "entityid");
            return this;
        }

        public Criteria andEntityidNotLike(String value) {
            addCriterion("EntityId not like", value, "entityid");
            return this;
        }

        public Criteria andEntityidIn(List values) {
            addCriterion("EntityId in", values, "entityid");
            return this;
        }

        public Criteria andEntityidNotIn(List values) {
            addCriterion("EntityId not in", values, "entityid");
            return this;
        }

        public Criteria andEntityidBetween(String value1, String value2) {
            addCriterion("EntityId between", value1, value2, "entityid");
            return this;
        }

        public Criteria andEntityidNotBetween(String value1, String value2) {
            addCriterion("EntityId not between", value1, value2, "entityid");
            return this;
        }
    }
}