package com.changan.mesinterface.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DegasserprocdataExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public DegasserprocdataExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    protected DegasserprocdataExample(DegasserprocdataExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andFIdIsNull() {
            addCriterion("F_ID is null");
            return this;
        }

        public Criteria andFIdIsNotNull() {
            addCriterion("F_ID is not null");
            return this;
        }

        public Criteria andFIdEqualTo(Integer value) {
            addCriterion("F_ID =", value, "fId");
            return this;
        }

        public Criteria andFIdNotEqualTo(Integer value) {
            addCriterion("F_ID <>", value, "fId");
            return this;
        }

        public Criteria andFIdGreaterThan(Integer value) {
            addCriterion("F_ID >", value, "fId");
            return this;
        }

        public Criteria andFIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("F_ID >=", value, "fId");
            return this;
        }

        public Criteria andFIdLessThan(Integer value) {
            addCriterion("F_ID <", value, "fId");
            return this;
        }

        public Criteria andFIdLessThanOrEqualTo(Integer value) {
            addCriterion("F_ID <=", value, "fId");
            return this;
        }

        public Criteria andFIdIn(List values) {
            addCriterion("F_ID in", values, "fId");
            return this;
        }

        public Criteria andFIdNotIn(List values) {
            addCriterion("F_ID not in", values, "fId");
            return this;
        }

        public Criteria andFIdBetween(Integer value1, Integer value2) {
            addCriterion("F_ID between", value1, value2, "fId");
            return this;
        }

        public Criteria andFIdNotBetween(Integer value1, Integer value2) {
            addCriterion("F_ID not between", value1, value2, "fId");
            return this;
        }

        public Criteria andFLineidIsNull() {
            addCriterion("F_LineID is null");
            return this;
        }

        public Criteria andFLineidIsNotNull() {
            addCriterion("F_LineID is not null");
            return this;
        }

        public Criteria andFLineidEqualTo(String value) {
            addCriterion("F_LineID =", value, "fLineid");
            return this;
        }

        public Criteria andFLineidNotEqualTo(String value) {
            addCriterion("F_LineID <>", value, "fLineid");
            return this;
        }

        public Criteria andFLineidGreaterThan(String value) {
            addCriterion("F_LineID >", value, "fLineid");
            return this;
        }

        public Criteria andFLineidGreaterThanOrEqualTo(String value) {
            addCriterion("F_LineID >=", value, "fLineid");
            return this;
        }

        public Criteria andFLineidLessThan(String value) {
            addCriterion("F_LineID <", value, "fLineid");
            return this;
        }

        public Criteria andFLineidLessThanOrEqualTo(String value) {
            addCriterion("F_LineID <=", value, "fLineid");
            return this;
        }

        public Criteria andFLineidLike(String value) {
            addCriterion("F_LineID like", value, "fLineid");
            return this;
        }

        public Criteria andFLineidNotLike(String value) {
            addCriterion("F_LineID not like", value, "fLineid");
            return this;
        }

        public Criteria andFLineidIn(List values) {
            addCriterion("F_LineID in", values, "fLineid");
            return this;
        }

        public Criteria andFLineidNotIn(List values) {
            addCriterion("F_LineID not in", values, "fLineid");
            return this;
        }

        public Criteria andFLineidBetween(String value1, String value2) {
            addCriterion("F_LineID between", value1, value2, "fLineid");
            return this;
        }

        public Criteria andFLineidNotBetween(String value1, String value2) {
            addCriterion("F_LineID not between", value1, value2, "fLineid");
            return this;
        }

        public Criteria andFStationnameIsNull() {
            addCriterion("F_StationName is null");
            return this;
        }

        public Criteria andFStationnameIsNotNull() {
            addCriterion("F_StationName is not null");
            return this;
        }

        public Criteria andFStationnameEqualTo(String value) {
            addCriterion("F_StationName =", value, "fStationname");
            return this;
        }

        public Criteria andFStationnameNotEqualTo(String value) {
            addCriterion("F_StationName <>", value, "fStationname");
            return this;
        }

        public Criteria andFStationnameGreaterThan(String value) {
            addCriterion("F_StationName >", value, "fStationname");
            return this;
        }

        public Criteria andFStationnameGreaterThanOrEqualTo(String value) {
            addCriterion("F_StationName >=", value, "fStationname");
            return this;
        }

        public Criteria andFStationnameLessThan(String value) {
            addCriterion("F_StationName <", value, "fStationname");
            return this;
        }

        public Criteria andFStationnameLessThanOrEqualTo(String value) {
            addCriterion("F_StationName <=", value, "fStationname");
            return this;
        }

        public Criteria andFStationnameLike(String value) {
            addCriterion("F_StationName like", value, "fStationname");
            return this;
        }

        public Criteria andFStationnameNotLike(String value) {
            addCriterion("F_StationName not like", value, "fStationname");
            return this;
        }

        public Criteria andFStationnameIn(List values) {
            addCriterion("F_StationName in", values, "fStationname");
            return this;
        }

        public Criteria andFStationnameNotIn(List values) {
            addCriterion("F_StationName not in", values, "fStationname");
            return this;
        }

        public Criteria andFStationnameBetween(String value1, String value2) {
            addCriterion("F_StationName between", value1, value2, "fStationname");
            return this;
        }

        public Criteria andFStationnameNotBetween(String value1, String value2) {
            addCriterion("F_StationName not between", value1, value2, "fStationname");
            return this;
        }

        public Criteria andFMaschinenidIsNull() {
            addCriterion("F_MaschinenID is null");
            return this;
        }

        public Criteria andFMaschinenidIsNotNull() {
            addCriterion("F_MaschinenID is not null");
            return this;
        }

        public Criteria andFMaschinenidEqualTo(String value) {
            addCriterion("F_MaschinenID =", value, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidNotEqualTo(String value) {
            addCriterion("F_MaschinenID <>", value, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidGreaterThan(String value) {
            addCriterion("F_MaschinenID >", value, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidGreaterThanOrEqualTo(String value) {
            addCriterion("F_MaschinenID >=", value, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidLessThan(String value) {
            addCriterion("F_MaschinenID <", value, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidLessThanOrEqualTo(String value) {
            addCriterion("F_MaschinenID <=", value, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidLike(String value) {
            addCriterion("F_MaschinenID like", value, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidNotLike(String value) {
            addCriterion("F_MaschinenID not like", value, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidIn(List values) {
            addCriterion("F_MaschinenID in", values, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidNotIn(List values) {
            addCriterion("F_MaschinenID not in", values, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidBetween(String value1, String value2) {
            addCriterion("F_MaschinenID between", value1, value2, "fMaschinenid");
            return this;
        }

        public Criteria andFMaschinenidNotBetween(String value1, String value2) {
            addCriterion("F_MaschinenID not between", value1, value2, "fMaschinenid");
            return this;
        }

        public Criteria andFDevicenameIsNull() {
            addCriterion("F_DeviceName is null");
            return this;
        }

        public Criteria andFDevicenameIsNotNull() {
            addCriterion("F_DeviceName is not null");
            return this;
        }

        public Criteria andFDevicenameEqualTo(String value) {
            addCriterion("F_DeviceName =", value, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameNotEqualTo(String value) {
            addCriterion("F_DeviceName <>", value, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameGreaterThan(String value) {
            addCriterion("F_DeviceName >", value, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameGreaterThanOrEqualTo(String value) {
            addCriterion("F_DeviceName >=", value, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameLessThan(String value) {
            addCriterion("F_DeviceName <", value, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameLessThanOrEqualTo(String value) {
            addCriterion("F_DeviceName <=", value, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameLike(String value) {
            addCriterion("F_DeviceName like", value, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameNotLike(String value) {
            addCriterion("F_DeviceName not like", value, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameIn(List values) {
            addCriterion("F_DeviceName in", values, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameNotIn(List values) {
            addCriterion("F_DeviceName not in", values, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameBetween(String value1, String value2) {
            addCriterion("F_DeviceName between", value1, value2, "fDevicename");
            return this;
        }

        public Criteria andFDevicenameNotBetween(String value1, String value2) {
            addCriterion("F_DeviceName not between", value1, value2, "fDevicename");
            return this;
        }

        public Criteria andFRfididIsNull() {
            addCriterion("F_RFIDID is null");
            return this;
        }

        public Criteria andFRfididIsNotNull() {
            addCriterion("F_RFIDID is not null");
            return this;
        }

        public Criteria andFRfididEqualTo(String value) {
            addCriterion("F_RFIDID =", value, "fRfidid");
            return this;
        }

        public Criteria andFRfididNotEqualTo(String value) {
            addCriterion("F_RFIDID <>", value, "fRfidid");
            return this;
        }

        public Criteria andFRfididGreaterThan(String value) {
            addCriterion("F_RFIDID >", value, "fRfidid");
            return this;
        }

        public Criteria andFRfididGreaterThanOrEqualTo(String value) {
            addCriterion("F_RFIDID >=", value, "fRfidid");
            return this;
        }

        public Criteria andFRfididLessThan(String value) {
            addCriterion("F_RFIDID <", value, "fRfidid");
            return this;
        }

        public Criteria andFRfididLessThanOrEqualTo(String value) {
            addCriterion("F_RFIDID <=", value, "fRfidid");
            return this;
        }

        public Criteria andFRfididLike(String value) {
            addCriterion("F_RFIDID like", value, "fRfidid");
            return this;
        }

        public Criteria andFRfididNotLike(String value) {
            addCriterion("F_RFIDID not like", value, "fRfidid");
            return this;
        }

        public Criteria andFRfididIn(List values) {
            addCriterion("F_RFIDID in", values, "fRfidid");
            return this;
        }

        public Criteria andFRfididNotIn(List values) {
            addCriterion("F_RFIDID not in", values, "fRfidid");
            return this;
        }

        public Criteria andFRfididBetween(String value1, String value2) {
            addCriterion("F_RFIDID between", value1, value2, "fRfidid");
            return this;
        }

        public Criteria andFRfididNotBetween(String value1, String value2) {
            addCriterion("F_RFIDID not between", value1, value2, "fRfidid");
            return this;
        }

        public Criteria andFPartidIsNull() {
            addCriterion("F_PartID is null");
            return this;
        }

        public Criteria andFPartidIsNotNull() {
            addCriterion("F_PartID is not null");
            return this;
        }

        public Criteria andFPartidEqualTo(String value) {
            addCriterion("F_PartID =", value, "fPartid");
            return this;
        }

        public Criteria andFPartidNotEqualTo(String value) {
            addCriterion("F_PartID <>", value, "fPartid");
            return this;
        }

        public Criteria andFPartidGreaterThan(String value) {
            addCriterion("F_PartID >", value, "fPartid");
            return this;
        }

        public Criteria andFPartidGreaterThanOrEqualTo(String value) {
            addCriterion("F_PartID >=", value, "fPartid");
            return this;
        }

        public Criteria andFPartidLessThan(String value) {
            addCriterion("F_PartID <", value, "fPartid");
            return this;
        }

        public Criteria andFPartidLessThanOrEqualTo(String value) {
            addCriterion("F_PartID <=", value, "fPartid");
            return this;
        }

        public Criteria andFPartidLike(String value) {
            addCriterion("F_PartID like", value, "fPartid");
            return this;
        }

        public Criteria andFPartidNotLike(String value) {
            addCriterion("F_PartID not like", value, "fPartid");
            return this;
        }

        public Criteria andFPartidIn(List values) {
            addCriterion("F_PartID in", values, "fPartid");
            return this;
        }

        public Criteria andFPartidNotIn(List values) {
            addCriterion("F_PartID not in", values, "fPartid");
            return this;
        }

        public Criteria andFPartidBetween(String value1, String value2) {
            addCriterion("F_PartID between", value1, value2, "fPartid");
            return this;
        }

        public Criteria andFPartidNotBetween(String value1, String value2) {
            addCriterion("F_PartID not between", value1, value2, "fPartid");
            return this;
        }

        public Criteria andFObjectivecyctimeIsNull() {
            addCriterion("F_ObjectiveCycTime is null");
            return this;
        }

        public Criteria andFObjectivecyctimeIsNotNull() {
            addCriterion("F_ObjectiveCycTime is not null");
            return this;
        }

        public Criteria andFObjectivecyctimeEqualTo(String value) {
            addCriterion("F_ObjectiveCycTime =", value, "fObjectivecyctime");
            return this;
        }

        public Criteria andFObjectivecyctimeNotEqualTo(String value) {
            addCriterion("F_ObjectiveCycTime <>", value, "fObjectivecyctime");
            return this;
        }

        public Criteria andFObjectivecyctimeGreaterThan(String value) {
            addCriterion("F_ObjectiveCycTime >", value, "fObjectivecyctime");
            return this;
        }

        public Criteria andFObjectivecyctimeGreaterThanOrEqualTo(String value) {
            addCriterion("F_ObjectiveCycTime >=", value, "fObjectivecyctime");
            return this;
        }

        public Criteria andFObjectivecyctimeLessThan(String value) {
            addCriterion("F_ObjectiveCycTime <", value, "fObjectivecyctime");
            return this;
        }

        public Criteria andFObjectivecyctimeLessThanOrEqualTo(String value) {
            addCriterion("F_ObjectiveCycTime <=", value, "fObjectivecyctime");
            return this;
        }

        public Criteria andFObjectivecyctimeLike(String value) {
            addCriterion("F_ObjectiveCycTime like", value, "fObjectivecyctime");
            return this;
        }

        public Criteria andFObjectivecyctimeNotLike(String value) {
            addCriterion("F_ObjectiveCycTime not like", value, "fObjectivecyctime");
            return this;
        }

        public Criteria andFObjectivecyctimeIn(List values) {
            addCriterion("F_ObjectiveCycTime in", values, "fObjectivecyctime");
            return this;
        }

        public Criteria andFObjectivecyctimeNotIn(List values) {
            addCriterion("F_ObjectiveCycTime not in", values, "fObjectivecyctime");
            return this;
        }

        public Criteria andFObjectivecyctimeBetween(String value1, String value2) {
            addCriterion("F_ObjectiveCycTime between", value1, value2, "fObjectivecyctime");
            return this;
        }

        public Criteria andFObjectivecyctimeNotBetween(String value1, String value2) {
            addCriterion("F_ObjectiveCycTime not between", value1, value2, "fObjectivecyctime");
            return this;
        }

        public Criteria andFRealcyctimeIsNull() {
            addCriterion("F_RealCycTime is null");
            return this;
        }

        public Criteria andFRealcyctimeIsNotNull() {
            addCriterion("F_RealCycTime is not null");
            return this;
        }

        public Criteria andFRealcyctimeEqualTo(String value) {
            addCriterion("F_RealCycTime =", value, "fRealcyctime");
            return this;
        }

        public Criteria andFRealcyctimeNotEqualTo(String value) {
            addCriterion("F_RealCycTime <>", value, "fRealcyctime");
            return this;
        }

        public Criteria andFRealcyctimeGreaterThan(String value) {
            addCriterion("F_RealCycTime >", value, "fRealcyctime");
            return this;
        }

        public Criteria andFRealcyctimeGreaterThanOrEqualTo(String value) {
            addCriterion("F_RealCycTime >=", value, "fRealcyctime");
            return this;
        }

        public Criteria andFRealcyctimeLessThan(String value) {
            addCriterion("F_RealCycTime <", value, "fRealcyctime");
            return this;
        }

        public Criteria andFRealcyctimeLessThanOrEqualTo(String value) {
            addCriterion("F_RealCycTime <=", value, "fRealcyctime");
            return this;
        }

        public Criteria andFRealcyctimeLike(String value) {
            addCriterion("F_RealCycTime like", value, "fRealcyctime");
            return this;
        }

        public Criteria andFRealcyctimeNotLike(String value) {
            addCriterion("F_RealCycTime not like", value, "fRealcyctime");
            return this;
        }

        public Criteria andFRealcyctimeIn(List values) {
            addCriterion("F_RealCycTime in", values, "fRealcyctime");
            return this;
        }

        public Criteria andFRealcyctimeNotIn(List values) {
            addCriterion("F_RealCycTime not in", values, "fRealcyctime");
            return this;
        }

        public Criteria andFRealcyctimeBetween(String value1, String value2) {
            addCriterion("F_RealCycTime between", value1, value2, "fRealcyctime");
            return this;
        }

        public Criteria andFRealcyctimeNotBetween(String value1, String value2) {
            addCriterion("F_RealCycTime not between", value1, value2, "fRealcyctime");
            return this;
        }

        public Criteria andFCheckparameterIsNull() {
            addCriterion("F_CheckParameter is null");
            return this;
        }

        public Criteria andFCheckparameterIsNotNull() {
            addCriterion("F_CheckParameter is not null");
            return this;
        }

        public Criteria andFCheckparameterEqualTo(String value) {
            addCriterion("F_CheckParameter =", value, "fCheckparameter");
            return this;
        }

        public Criteria andFCheckparameterNotEqualTo(String value) {
            addCriterion("F_CheckParameter <>", value, "fCheckparameter");
            return this;
        }

        public Criteria andFCheckparameterGreaterThan(String value) {
            addCriterion("F_CheckParameter >", value, "fCheckparameter");
            return this;
        }

        public Criteria andFCheckparameterGreaterThanOrEqualTo(String value) {
            addCriterion("F_CheckParameter >=", value, "fCheckparameter");
            return this;
        }

        public Criteria andFCheckparameterLessThan(String value) {
            addCriterion("F_CheckParameter <", value, "fCheckparameter");
            return this;
        }

        public Criteria andFCheckparameterLessThanOrEqualTo(String value) {
            addCriterion("F_CheckParameter <=", value, "fCheckparameter");
            return this;
        }

        public Criteria andFCheckparameterLike(String value) {
            addCriterion("F_CheckParameter like", value, "fCheckparameter");
            return this;
        }

        public Criteria andFCheckparameterNotLike(String value) {
            addCriterion("F_CheckParameter not like", value, "fCheckparameter");
            return this;
        }

        public Criteria andFCheckparameterIn(List values) {
            addCriterion("F_CheckParameter in", values, "fCheckparameter");
            return this;
        }

        public Criteria andFCheckparameterNotIn(List values) {
            addCriterion("F_CheckParameter not in", values, "fCheckparameter");
            return this;
        }

        public Criteria andFCheckparameterBetween(String value1, String value2) {
            addCriterion("F_CheckParameter between", value1, value2, "fCheckparameter");
            return this;
        }

        public Criteria andFCheckparameterNotBetween(String value1, String value2) {
            addCriterion("F_CheckParameter not between", value1, value2, "fCheckparameter");
            return this;
        }

        public Criteria andFQualityvalueIsNull() {
            addCriterion("F_QualityValue is null");
            return this;
        }

        public Criteria andFQualityvalueIsNotNull() {
            addCriterion("F_QualityValue is not null");
            return this;
        }

        public Criteria andFQualityvalueEqualTo(String value) {
            addCriterion("F_QualityValue =", value, "fQualityvalue");
            return this;
        }

        public Criteria andFQualityvalueNotEqualTo(String value) {
            addCriterion("F_QualityValue <>", value, "fQualityvalue");
            return this;
        }

        public Criteria andFQualityvalueGreaterThan(String value) {
            addCriterion("F_QualityValue >", value, "fQualityvalue");
            return this;
        }

        public Criteria andFQualityvalueGreaterThanOrEqualTo(String value) {
            addCriterion("F_QualityValue >=", value, "fQualityvalue");
            return this;
        }

        public Criteria andFQualityvalueLessThan(String value) {
            addCriterion("F_QualityValue <", value, "fQualityvalue");
            return this;
        }

        public Criteria andFQualityvalueLessThanOrEqualTo(String value) {
            addCriterion("F_QualityValue <=", value, "fQualityvalue");
            return this;
        }

        public Criteria andFQualityvalueLike(String value) {
            addCriterion("F_QualityValue like", value, "fQualityvalue");
            return this;
        }

        public Criteria andFQualityvalueNotLike(String value) {
            addCriterion("F_QualityValue not like", value, "fQualityvalue");
            return this;
        }

        public Criteria andFQualityvalueIn(List values) {
            addCriterion("F_QualityValue in", values, "fQualityvalue");
            return this;
        }

        public Criteria andFQualityvalueNotIn(List values) {
            addCriterion("F_QualityValue not in", values, "fQualityvalue");
            return this;
        }

        public Criteria andFQualityvalueBetween(String value1, String value2) {
            addCriterion("F_QualityValue between", value1, value2, "fQualityvalue");
            return this;
        }

        public Criteria andFQualityvalueNotBetween(String value1, String value2) {
            addCriterion("F_QualityValue not between", value1, value2, "fQualityvalue");
            return this;
        }

        public Criteria andFUnitIsNull() {
            addCriterion("F_Unit is null");
            return this;
        }

        public Criteria andFUnitIsNotNull() {
            addCriterion("F_Unit is not null");
            return this;
        }

        public Criteria andFUnitEqualTo(String value) {
            addCriterion("F_Unit =", value, "fUnit");
            return this;
        }

        public Criteria andFUnitNotEqualTo(String value) {
            addCriterion("F_Unit <>", value, "fUnit");
            return this;
        }

        public Criteria andFUnitGreaterThan(String value) {
            addCriterion("F_Unit >", value, "fUnit");
            return this;
        }

        public Criteria andFUnitGreaterThanOrEqualTo(String value) {
            addCriterion("F_Unit >=", value, "fUnit");
            return this;
        }

        public Criteria andFUnitLessThan(String value) {
            addCriterion("F_Unit <", value, "fUnit");
            return this;
        }

        public Criteria andFUnitLessThanOrEqualTo(String value) {
            addCriterion("F_Unit <=", value, "fUnit");
            return this;
        }

        public Criteria andFUnitLike(String value) {
            addCriterion("F_Unit like", value, "fUnit");
            return this;
        }

        public Criteria andFUnitNotLike(String value) {
            addCriterion("F_Unit not like", value, "fUnit");
            return this;
        }

        public Criteria andFUnitIn(List values) {
            addCriterion("F_Unit in", values, "fUnit");
            return this;
        }

        public Criteria andFUnitNotIn(List values) {
            addCriterion("F_Unit not in", values, "fUnit");
            return this;
        }

        public Criteria andFUnitBetween(String value1, String value2) {
            addCriterion("F_Unit between", value1, value2, "fUnit");
            return this;
        }

        public Criteria andFUnitNotBetween(String value1, String value2) {
            addCriterion("F_Unit not between", value1, value2, "fUnit");
            return this;
        }

        public Criteria andFTimeIsNull() {
            addCriterion("F_Time is null");
            return this;
        }

        public Criteria andFTimeIsNotNull() {
            addCriterion("F_Time is not null");
            return this;
        }

        public Criteria andFTimeEqualTo(Date value) {
            addCriterion("F_Time =", value, "fTime");
            return this;
        }

        public Criteria andFTimeNotEqualTo(Date value) {
            addCriterion("F_Time <>", value, "fTime");
            return this;
        }

        public Criteria andFTimeGreaterThan(Date value) {
            addCriterion("F_Time >", value, "fTime");
            return this;
        }

        public Criteria andFTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("F_Time >=", value, "fTime");
            return this;
        }

        public Criteria andFTimeLessThan(Date value) {
            addCriterion("F_Time <", value, "fTime");
            return this;
        }

        public Criteria andFTimeLessThanOrEqualTo(Date value) {
            addCriterion("F_Time <=", value, "fTime");
            return this;
        }

        public Criteria andFTimeIn(List values) {
            addCriterion("F_Time in", values, "fTime");
            return this;
        }

        public Criteria andFTimeNotIn(List values) {
            addCriterion("F_Time not in", values, "fTime");
            return this;
        }

        public Criteria andFTimeBetween(Date value1, Date value2) {
            addCriterion("F_Time between", value1, value2, "fTime");
            return this;
        }

        public Criteria andFTimeNotBetween(Date value1, Date value2) {
            addCriterion("F_Time not between", value1, value2, "fTime");
            return this;
        }

        public Criteria andFIssyncIsNull() {
            addCriterion("F_IsSync is null");
            return this;
        }

        public Criteria andFIssyncIsNotNull() {
            addCriterion("F_IsSync is not null");
            return this;
        }

        public Criteria andFIssyncEqualTo(Integer value) {
            addCriterion("F_IsSync =", value, "fIssync");
            return this;
        }

        public Criteria andFIssyncNotEqualTo(Integer value) {
            addCriterion("F_IsSync <>", value, "fIssync");
            return this;
        }

        public Criteria andFIssyncGreaterThan(Integer value) {
            addCriterion("F_IsSync >", value, "fIssync");
            return this;
        }

        public Criteria andFIssyncGreaterThanOrEqualTo(Integer value) {
            addCriterion("F_IsSync >=", value, "fIssync");
            return this;
        }

        public Criteria andFIssyncLessThan(Integer value) {
            addCriterion("F_IsSync <", value, "fIssync");
            return this;
        }

        public Criteria andFIssyncLessThanOrEqualTo(Integer value) {
            addCriterion("F_IsSync <=", value, "fIssync");
            return this;
        }

        public Criteria andFIssyncIn(List values) {
            addCriterion("F_IsSync in", values, "fIssync");
            return this;
        }

        public Criteria andFIssyncNotIn(List values) {
            addCriterion("F_IsSync not in", values, "fIssync");
            return this;
        }

        public Criteria andFIssyncBetween(Integer value1, Integer value2) {
            addCriterion("F_IsSync between", value1, value2, "fIssync");
            return this;
        }

        public Criteria andFIssyncNotBetween(Integer value1, Integer value2) {
            addCriterion("F_IsSync not between", value1, value2, "fIssync");
            return this;
        }

        public Criteria andEntityidIsNull() {
            addCriterion("EntityId is null");
            return this;
        }

        public Criteria andEntityidIsNotNull() {
            addCriterion("EntityId is not null");
            return this;
        }

        public Criteria andEntityidEqualTo(String value) {
            addCriterion("EntityId =", value, "entityid");
            return this;
        }

        public Criteria andEntityidNotEqualTo(String value) {
            addCriterion("EntityId <>", value, "entityid");
            return this;
        }

        public Criteria andEntityidGreaterThan(String value) {
            addCriterion("EntityId >", value, "entityid");
            return this;
        }

        public Criteria andEntityidGreaterThanOrEqualTo(String value) {
            addCriterion("EntityId >=", value, "entityid");
            return this;
        }

        public Criteria andEntityidLessThan(String value) {
            addCriterion("EntityId <", value, "entityid");
            return this;
        }

        public Criteria andEntityidLessThanOrEqualTo(String value) {
            addCriterion("EntityId <=", value, "entityid");
            return this;
        }

        public Criteria andEntityidLike(String value) {
            addCriterion("EntityId like", value, "entityid");
            return this;
        }

        public Criteria andEntityidNotLike(String value) {
            addCriterion("EntityId not like", value, "entityid");
            return this;
        }

        public Criteria andEntityidIn(List values) {
            addCriterion("EntityId in", values, "entityid");
            return this;
        }

        public Criteria andEntityidNotIn(List values) {
            addCriterion("EntityId not in", values, "entityid");
            return this;
        }

        public Criteria andEntityidBetween(String value1, String value2) {
            addCriterion("EntityId between", value1, value2, "entityid");
            return this;
        }

        public Criteria andEntityidNotBetween(String value1, String value2) {
            addCriterion("EntityId not between", value1, value2, "entityid");
            return this;
        }
    }
}