package com.changan.mesinterface.model;

import java.util.Date;

public class Degasserprocdata {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserprocdata.F_ID
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    private Integer fId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserprocdata.F_LineID
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    private String fLineid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserprocdata.F_StationName
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    private String fStationname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserprocdata.F_MaschinenID
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    private String fMaschinenid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserprocdata.F_DeviceName
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    private String fDevicename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserprocdata.F_RFIDID
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    private String fRfidid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserprocdata.F_PartID
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    private String fPartid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserprocdata.F_ObjectiveCycTime
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    private String fObjectivecyctime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserprocdata.F_RealCycTime
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    private String fRealcyctime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserprocdata.F_CheckParameter
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    private String fCheckparameter;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserprocdata.F_QualityValue
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    private String fQualityvalue;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserprocdata.F_Unit
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    private String fUnit;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserprocdata.F_Time
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    private Date fTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserprocdata.F_IsSync
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    private Integer fIssync;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column degasserprocdata.EntityId
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    private String entityid;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserprocdata.F_ID
     *
     * @return the value of degasserprocdata.F_ID
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserprocdata.F_ID
     *
     * @param fId the value for degasserprocdata.F_ID
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserprocdata.F_LineID
     *
     * @return the value of degasserprocdata.F_LineID
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public String getfLineid() {
        return fLineid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserprocdata.F_LineID
     *
     * @param fLineid the value for degasserprocdata.F_LineID
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void setfLineid(String fLineid) {
        this.fLineid = fLineid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserprocdata.F_StationName
     *
     * @return the value of degasserprocdata.F_StationName
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public String getfStationname() {
        return fStationname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserprocdata.F_StationName
     *
     * @param fStationname the value for degasserprocdata.F_StationName
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void setfStationname(String fStationname) {
        this.fStationname = fStationname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserprocdata.F_MaschinenID
     *
     * @return the value of degasserprocdata.F_MaschinenID
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public String getfMaschinenid() {
        return fMaschinenid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserprocdata.F_MaschinenID
     *
     * @param fMaschinenid the value for degasserprocdata.F_MaschinenID
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void setfMaschinenid(String fMaschinenid) {
        this.fMaschinenid = fMaschinenid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserprocdata.F_DeviceName
     *
     * @return the value of degasserprocdata.F_DeviceName
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public String getfDevicename() {
        return fDevicename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserprocdata.F_DeviceName
     *
     * @param fDevicename the value for degasserprocdata.F_DeviceName
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void setfDevicename(String fDevicename) {
        this.fDevicename = fDevicename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserprocdata.F_RFIDID
     *
     * @return the value of degasserprocdata.F_RFIDID
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public String getfRfidid() {
        return fRfidid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserprocdata.F_RFIDID
     *
     * @param fRfidid the value for degasserprocdata.F_RFIDID
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void setfRfidid(String fRfidid) {
        this.fRfidid = fRfidid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserprocdata.F_PartID
     *
     * @return the value of degasserprocdata.F_PartID
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public String getfPartid() {
        return fPartid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserprocdata.F_PartID
     *
     * @param fPartid the value for degasserprocdata.F_PartID
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void setfPartid(String fPartid) {
        this.fPartid = fPartid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserprocdata.F_ObjectiveCycTime
     *
     * @return the value of degasserprocdata.F_ObjectiveCycTime
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public String getfObjectivecyctime() {
        return fObjectivecyctime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserprocdata.F_ObjectiveCycTime
     *
     * @param fObjectivecyctime the value for degasserprocdata.F_ObjectiveCycTime
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void setfObjectivecyctime(String fObjectivecyctime) {
        this.fObjectivecyctime = fObjectivecyctime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserprocdata.F_RealCycTime
     *
     * @return the value of degasserprocdata.F_RealCycTime
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public String getfRealcyctime() {
        return fRealcyctime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserprocdata.F_RealCycTime
     *
     * @param fRealcyctime the value for degasserprocdata.F_RealCycTime
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void setfRealcyctime(String fRealcyctime) {
        this.fRealcyctime = fRealcyctime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserprocdata.F_CheckParameter
     *
     * @return the value of degasserprocdata.F_CheckParameter
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public String getfCheckparameter() {
        return fCheckparameter;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserprocdata.F_CheckParameter
     *
     * @param fCheckparameter the value for degasserprocdata.F_CheckParameter
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void setfCheckparameter(String fCheckparameter) {
        this.fCheckparameter = fCheckparameter;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserprocdata.F_QualityValue
     *
     * @return the value of degasserprocdata.F_QualityValue
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public String getfQualityvalue() {
        return fQualityvalue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserprocdata.F_QualityValue
     *
     * @param fQualityvalue the value for degasserprocdata.F_QualityValue
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void setfQualityvalue(String fQualityvalue) {
        this.fQualityvalue = fQualityvalue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserprocdata.F_Unit
     *
     * @return the value of degasserprocdata.F_Unit
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public String getfUnit() {
        return fUnit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserprocdata.F_Unit
     *
     * @param fUnit the value for degasserprocdata.F_Unit
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void setfUnit(String fUnit) {
        this.fUnit = fUnit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserprocdata.F_Time
     *
     * @return the value of degasserprocdata.F_Time
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public Date getfTime() {
        return fTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserprocdata.F_Time
     *
     * @param fTime the value for degasserprocdata.F_Time
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void setfTime(Date fTime) {
        this.fTime = fTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserprocdata.F_IsSync
     *
     * @return the value of degasserprocdata.F_IsSync
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public Integer getfIssync() {
        return fIssync;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserprocdata.F_IsSync
     *
     * @param fIssync the value for degasserprocdata.F_IsSync
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void setfIssync(Integer fIssync) {
        this.fIssync = fIssync;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column degasserprocdata.EntityId
     *
     * @return the value of degasserprocdata.EntityId
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public String getEntityid() {
        return entityid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column degasserprocdata.EntityId
     *
     * @param entityid the value for degasserprocdata.EntityId
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void setEntityid(String entityid) {
        this.entityid = entityid;
    }
}