package com.changan.plcinterface.model;

import java.util.Date;

public class BasicdeviceKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cgcdevice.Deviceid
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    private Integer deviceid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cgcdevice.PLCtime
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    private Date plctime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cgcdevice.Wprecordvalue
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    private Long wprecordvalue;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cgcdevice.Deviceid
     *
     * @return the value of cgcdevice.Deviceid
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public Integer getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cgcdevice.Deviceid
     *
     * @param deviceid the value for cgcdevice.Deviceid
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public void setDeviceid(Integer deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cgcdevice.PLCtime
     *
     * @return the value of cgcdevice.PLCtime
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public Date getPlctime() {
        return plctime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cgcdevice.PLCtime
     *
     * @param plctime the value for cgcdevice.PLCtime
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public void setPlctime(Date plctime) {
        this.plctime = plctime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cgcdevice.Wprecordvalue
     *
     * @return the value of cgcdevice.Wprecordvalue
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public Long getWprecordvalue() {
        return wprecordvalue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cgcdevice.Wprecordvalue
     *
     * @param wprecordvalue the value for cgcdevice.Wprecordvalue
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public void setWprecordvalue(Long wprecordvalue) {
        this.wprecordvalue = wprecordvalue;
    }
}