package com.changan.plcinterface.model;

public class Cgcdevice extends Basicdevice {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column cgcdevice.Devicename
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	private String devicename;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column cgcdevice.Devicestatus
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	private Long devicestatus;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column cgcdevice.Workpiecename
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	private String workpiecename;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column cgcdevice.Toolcode
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	private Integer toolcode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column cgcdevice.Faultcode
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	private Long faultcode;
	
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column cgcdevice.Processcode
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	private Integer processcode;
	
	private String processName;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column cgcdevice.Devicename
	 * @return  the value of cgcdevice.Devicename
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	public String getDevicename() {
		return devicename;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column cgcdevice.Devicename
	 * @param devicename  the value for cgcdevice.Devicename
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	public void setDevicename(String devicename) {
		this.devicename = devicename;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column cgcdevice.Devicestatus
	 * @return  the value of cgcdevice.Devicestatus
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	public Long getDevicestatus() {
		return devicestatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column cgcdevice.Devicestatus
	 * @param devicestatus  the value for cgcdevice.Devicestatus
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	public void setDevicestatus(Long devicestatus) {
		this.devicestatus = devicestatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column cgcdevice.Workpiecename
	 * @return  the value of cgcdevice.Workpiecename
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	public String getWorkpiecename() {
		return workpiecename;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column cgcdevice.Workpiecename
	 * @param workpiecename  the value for cgcdevice.Workpiecename
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	public void setWorkpiecename(String workpiecename) {
		this.workpiecename = workpiecename;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column cgcdevice.Toolcode
	 * @return  the value of cgcdevice.Toolcode
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	public Integer getToolcode() {
		return toolcode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column cgcdevice.Toolcode
	 * @param toolcode  the value for cgcdevice.Toolcode
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	public void setToolcode(Integer toolcode) {
		this.toolcode = toolcode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column cgcdevice.Faultcode
	 * @return  the value of cgcdevice.Faultcode
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	public Long getFaultcode() {
		return faultcode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column cgcdevice.Faultcode
	 * @param faultcode  the value for cgcdevice.Faultcode
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	public void setFaultcode(Long faultcode) {
		this.faultcode = faultcode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column cgcdevice.Processcode
	 * @return  the value of cgcdevice.Processcode
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	public Integer getProcesscode() {
		return processcode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column cgcdevice.Processcode
	 * @param processcode  the value for cgcdevice.Processcode
	 * @abatorgenerated  Fri Apr 15 21:39:55 CST 2016
	 */
	public void setProcesscode(Integer processcode) {
		this.processcode = processcode;
	}

	/**
	 * @return the processName
	 */
	public String getProcessName() {
		return processName;
	}

	/**
	 * @param processName the processName to set
	 */
	public void setProcessName(String processName) {
		this.processName = processName;
	}
}