package com.changan.plcinterface.model;

public class Machinedevice extends Basicdevice {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column machinedevice.Devicename
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    private String devicename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column machinedevice.Devicestatus
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    private Long devicestatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column machinedevice.Workpiecename
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    private String workpiecename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column machinedevice.Toolcode
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    private String toolcode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column machinedevice.Faultcode
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    private Long faultcode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column machinedevice.Processcode
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    private Integer processcode;

	private String processName;
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column machinedevice.Devicename
     *
     * @return the value of machinedevice.Devicename
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    public String getDevicename() {
        return devicename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column machinedevice.Devicename
     *
     * @param devicename the value for machinedevice.Devicename
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    public void setDevicename(String devicename) {
        this.devicename = devicename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column machinedevice.Devicestatus
     *
     * @return the value of machinedevice.Devicestatus
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    public Long getDevicestatus() {
        return devicestatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column machinedevice.Devicestatus
     *
     * @param devicestatus the value for machinedevice.Devicestatus
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    public void setDevicestatus(Long devicestatus) {
        this.devicestatus = devicestatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column machinedevice.Workpiecename
     *
     * @return the value of machinedevice.Workpiecename
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    public String getWorkpiecename() {
        return workpiecename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column machinedevice.Workpiecename
     *
     * @param workpiecename the value for machinedevice.Workpiecename
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    public void setWorkpiecename(String workpiecename) {
        this.workpiecename = workpiecename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column machinedevice.Toolcode
     *
     * @return the value of machinedevice.Toolcode
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    public String getToolcode() {
        return toolcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column machinedevice.Toolcode
     *
     * @param toolcode the value for machinedevice.Toolcode
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    public void setToolcode(String toolcode) {
        this.toolcode = toolcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column machinedevice.Faultcode
     *
     * @return the value of machinedevice.Faultcode
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    public Long getFaultcode() {
        return faultcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column machinedevice.Faultcode
     *
     * @param faultcode the value for machinedevice.Faultcode
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    public void setFaultcode(Long faultcode) {
        this.faultcode = faultcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column machinedevice.Processcode
     *
     * @return the value of machinedevice.Processcode
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    public Integer getProcesscode() {
        return processcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column machinedevice.Processcode
     *
     * @param processcode the value for machinedevice.Processcode
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    public void setProcesscode(Integer processcode) {
        this.processcode = processcode;
    }

	/**
	 * @return the processName
	 */
	public String getProcessName() {
		return processName;
	}

	/**
	 * @param processName the processName to set
	 */
	public void setProcessName(String processName) {
		this.processName = processName;
	}
}