package com.changan.plcinterface.model;

public class Shocksanddevice extends Basicdevice {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shocksanddevice.Devicename
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	private String devicename;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shocksanddevice.Devicestatus
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	private Long devicestatus;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shocksanddevice.Workpiecename
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	private String workpiecename;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shocksanddevice.Hammerpressure
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	private Float hammerpressure;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shocksanddevice.Hammertime
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	private Integer hammertime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shocksanddevice.Shocktime
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	private Integer shocktime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shocksanddevice.Faultcode
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	private Long faultcode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shocksanddevice.Processcode
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	private Integer processcode;
	private String processName;


	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shocksanddevice.Devicename
	 * @return  the value of shocksanddevice.Devicename
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public String getDevicename() {
		return devicename;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shocksanddevice.Devicename
	 * @param devicename  the value for shocksanddevice.Devicename
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public void setDevicename(String devicename) {
		this.devicename = devicename;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shocksanddevice.Devicestatus
	 * @return  the value of shocksanddevice.Devicestatus
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public Long getDevicestatus() {
		return devicestatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shocksanddevice.Devicestatus
	 * @param devicestatus  the value for shocksanddevice.Devicestatus
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public void setDevicestatus(Long devicestatus) {
		this.devicestatus = devicestatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shocksanddevice.Workpiecename
	 * @return  the value of shocksanddevice.Workpiecename
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public String getWorkpiecename() {
		return workpiecename;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shocksanddevice.Workpiecename
	 * @param workpiecename  the value for shocksanddevice.Workpiecename
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public void setWorkpiecename(String workpiecename) {
		this.workpiecename = workpiecename;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shocksanddevice.Hammerpressure
	 * @return  the value of shocksanddevice.Hammerpressure
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public Float getHammerpressure() {
		return hammerpressure;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shocksanddevice.Hammerpressure
	 * @param hammerpressure  the value for shocksanddevice.Hammerpressure
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public void setHammerpressure(Float hammerpressure) {
		this.hammerpressure = hammerpressure;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shocksanddevice.Hammertime
	 * @return  the value of shocksanddevice.Hammertime
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public Integer getHammertime() {
		return hammertime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shocksanddevice.Hammertime
	 * @param hammertime  the value for shocksanddevice.Hammertime
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public void setHammertime(Integer hammertime) {
		this.hammertime = hammertime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shocksanddevice.Shocktime
	 * @return  the value of shocksanddevice.Shocktime
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public Integer getShocktime() {
		return shocktime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shocksanddevice.Shocktime
	 * @param shocktime  the value for shocksanddevice.Shocktime
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public void setShocktime(Integer shocktime) {
		this.shocktime = shocktime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shocksanddevice.Faultcode
	 * @return  the value of shocksanddevice.Faultcode
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public Long getFaultcode() {
		return faultcode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shocksanddevice.Faultcode
	 * @param faultcode  the value for shocksanddevice.Faultcode
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public void setFaultcode(Long faultcode) {
		this.faultcode = faultcode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shocksanddevice.Processcode
	 * @return  the value of shocksanddevice.Processcode
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public Integer getProcesscode() {
		return processcode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shocksanddevice.Processcode
	 * @param processcode  the value for shocksanddevice.Processcode
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public void setProcesscode(Integer processcode) {
		this.processcode = processcode;
	}

	/**
	 * @return the processName
	 */
	public String getProcessName() {
		return processName;
	}

	/**
	 * @param processName the processName to set
	 */
	public void setProcessName(String processName) {
		this.processName = processName;
	}
}