package com.changan.plcinterface.model;

import java.util.Date;

public class ShocksanddeviceKey {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shocksanddevice.Deviceid
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	private Integer deviceid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shocksanddevice.PLCtime
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	private Date plctime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shocksanddevice.Wprecordvalue
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	private Long wprecordvalue;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shocksanddevice.Deviceid
	 * @return  the value of shocksanddevice.Deviceid
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public Integer getDeviceid() {
		return deviceid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shocksanddevice.Deviceid
	 * @param deviceid  the value for shocksanddevice.Deviceid
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public void setDeviceid(Integer deviceid) {
		this.deviceid = deviceid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shocksanddevice.PLCtime
	 * @return  the value of shocksanddevice.PLCtime
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public Date getPlctime() {
		return plctime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shocksanddevice.PLCtime
	 * @param plctime  the value for shocksanddevice.PLCtime
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public void setPlctime(Date plctime) {
		this.plctime = plctime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shocksanddevice.Wprecordvalue
	 * @return  the value of shocksanddevice.Wprecordvalue
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public Long getWprecordvalue() {
		return wprecordvalue;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shocksanddevice.Wprecordvalue
	 * @param wprecordvalue  the value for shocksanddevice.Wprecordvalue
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public void setWprecordvalue(Long wprecordvalue) {
		this.wprecordvalue = wprecordvalue;
	}
}