package com.changan.plcinterface.model;

public class Transferdevice extends Basicdevice {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column transferdevice.Devicename
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    private String devicename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column transferdevice.Devicestatus
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    private Long devicestatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column transferdevice.Workpiecename
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    private String workpiecename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column transferdevice.Faultcode
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    private Long faultcode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column transferdevice.Processcode
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    private Integer processcode;

	private String processName;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transferdevice.Devicename
     *
     * @return the value of transferdevice.Devicename
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public String getDevicename() {
        return devicename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transferdevice.Devicename
     *
     * @param devicename the value for transferdevice.Devicename
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public void setDevicename(String devicename) {
        this.devicename = devicename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transferdevice.Devicestatus
     *
     * @return the value of transferdevice.Devicestatus
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public Long getDevicestatus() {
        return devicestatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transferdevice.Devicestatus
     *
     * @param devicestatus the value for transferdevice.Devicestatus
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public void setDevicestatus(Long devicestatus) {
        this.devicestatus = devicestatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transferdevice.Workpiecename
     *
     * @return the value of transferdevice.Workpiecename
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public String getWorkpiecename() {
        return workpiecename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transferdevice.Workpiecename
     *
     * @param workpiecename the value for transferdevice.Workpiecename
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public void setWorkpiecename(String workpiecename) {
        this.workpiecename = workpiecename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transferdevice.Faultcode
     *
     * @return the value of transferdevice.Faultcode
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public Long getFaultcode() {
        return faultcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transferdevice.Faultcode
     *
     * @param faultcode the value for transferdevice.Faultcode
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public void setFaultcode(Long faultcode) {
        this.faultcode = faultcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transferdevice.Processcode
     *
     * @return the value of transferdevice.Processcode
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public Integer getProcesscode() {
        return processcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transferdevice.Processcode
     *
     * @param processcode the value for transferdevice.Processcode
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public void setProcesscode(Integer processcode) {
        this.processcode = processcode;
    }

	/**
	 * @return the processName
	 */
	public String getProcessName() {
		return processName;
	}

	/**
	 * @param processName the processName to set
	 */
	public void setProcessName(String processName) {
		this.processName = processName;
	}
}