package com.changan.plcinterface.model;

import java.util.Date;

public class TransferdeviceKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column transferdevice.Deviceid
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    private Integer deviceid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column transferdevice.PLCtime
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    private Date plctime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column transferdevice.Wprecordvalue
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    private Long wprecordvalue;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transferdevice.Deviceid
     *
     * @return the value of transferdevice.Deviceid
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public Integer getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transferdevice.Deviceid
     *
     * @param deviceid the value for transferdevice.Deviceid
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public void setDeviceid(Integer deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transferdevice.PLCtime
     *
     * @return the value of transferdevice.PLCtime
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public Date getPlctime() {
        return plctime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transferdevice.PLCtime
     *
     * @param plctime the value for transferdevice.PLCtime
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public void setPlctime(Date plctime) {
        this.plctime = plctime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transferdevice.Wprecordvalue
     *
     * @return the value of transferdevice.Wprecordvalue
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public Long getWprecordvalue() {
        return wprecordvalue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transferdevice.Wprecordvalue
     *
     * @param wprecordvalue the value for transferdevice.Wprecordvalue
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public void setWprecordvalue(Long wprecordvalue) {
        this.wprecordvalue = wprecordvalue;
    }
}