package com.changan.plcinterface.model;

public class WprecordinformationKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column wprecordinformation.Wpdataname
     *
     * @abatorgenerated Sun Mar 27 10:49:37 CST 2016
     */
    private String wpdataname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column wprecordinformation.Wprecordcode
     *
     * @abatorgenerated Sun Mar 27 10:49:37 CST 2016
     */
    private Integer wprecordcode;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column wprecordinformation.Wpdataname
     *
     * @return the value of wprecordinformation.Wpdataname
     *
     * @abatorgenerated Sun Mar 27 10:49:37 CST 2016
     */
    public String getWpdataname() {
        return wpdataname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column wprecordinformation.Wpdataname
     *
     * @param wpdataname the value for wprecordinformation.Wpdataname
     *
     * @abatorgenerated Sun Mar 27 10:49:37 CST 2016
     */
    public void setWpdataname(String wpdataname) {
        this.wpdataname = wpdataname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column wprecordinformation.Wprecordcode
     *
     * @return the value of wprecordinformation.Wprecordcode
     *
     * @abatorgenerated Sun Mar 27 10:49:37 CST 2016
     */
    public Integer getWprecordcode() {
        return wprecordcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column wprecordinformation.Wprecordcode
     *
     * @param wprecordcode the value for wprecordinformation.Wprecordcode
     *
     * @abatorgenerated Sun Mar 27 10:49:37 CST 2016
     */
    public void setWprecordcode(Integer wprecordcode) {
        this.wprecordcode = wprecordcode;
    }
}