package com.changan.plcinterface.model;

import java.util.Date;

public class Wprecordinformation extends WprecordinformationKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column wprecordinformation.Datatime
     *
     * @abatorgenerated Sun Mar 27 10:49:37 CST 2016
     */
    private Date datatime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column wprecordinformation.Recordstatus
     *
     * @abatorgenerated Sun Mar 27 10:49:37 CST 2016
     */
    private Boolean recordstatus;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column wprecordinformation.Datatime
     *
     * @return the value of wprecordinformation.Datatime
     *
     * @abatorgenerated Sun Mar 27 10:49:37 CST 2016
     */
    public Date getDatatime() {
        return datatime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column wprecordinformation.Datatime
     *
     * @param datatime the value for wprecordinformation.Datatime
     *
     * @abatorgenerated Sun Mar 27 10:49:37 CST 2016
     */
    public void setDatatime(Date datatime) {
        this.datatime = datatime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column wprecordinformation.Recordstatus
     *
     * @return the value of wprecordinformation.Recordstatus
     *
     * @abatorgenerated Sun Mar 27 10:49:37 CST 2016
     */
    public Boolean getRecordstatus() {
        return recordstatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column wprecordinformation.Recordstatus
     *
     * @param recordstatus the value for wprecordinformation.Recordstatus
     *
     * @abatorgenerated Sun Mar 27 10:49:37 CST 2016
     */
    public void setRecordstatus(Boolean recordstatus) {
        this.recordstatus = recordstatus;
    }
}