package com.changan.app.report.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TSparepartsAlarmExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public TSparepartsAlarmExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	protected TSparepartsAlarmExample(TSparepartsAlarmExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andDevicemetaidIsNull() {
			addCriterion("deviceMetaId is null");
			return this;
		}

		public Criteria andDevicemetaidIsNotNull() {
			addCriterion("deviceMetaId is not null");
			return this;
		}

		public Criteria andDevicemetaidEqualTo(Integer value) {
			addCriterion("deviceMetaId =", value, "devicemetaid");
			return this;
		}

		public Criteria andDevicemetaidNotEqualTo(Integer value) {
			addCriterion("deviceMetaId <>", value, "devicemetaid");
			return this;
		}

		public Criteria andDevicemetaidGreaterThan(Integer value) {
			addCriterion("deviceMetaId >", value, "devicemetaid");
			return this;
		}

		public Criteria andDevicemetaidGreaterThanOrEqualTo(Integer value) {
			addCriterion("deviceMetaId >=", value, "devicemetaid");
			return this;
		}

		public Criteria andDevicemetaidLessThan(Integer value) {
			addCriterion("deviceMetaId <", value, "devicemetaid");
			return this;
		}

		public Criteria andDevicemetaidLessThanOrEqualTo(Integer value) {
			addCriterion("deviceMetaId <=", value, "devicemetaid");
			return this;
		}

		public Criteria andDevicemetaidIn(List values) {
			addCriterion("deviceMetaId in", values, "devicemetaid");
			return this;
		}

		public Criteria andDevicemetaidNotIn(List values) {
			addCriterion("deviceMetaId not in", values, "devicemetaid");
			return this;
		}

		public Criteria andDevicemetaidBetween(Integer value1, Integer value2) {
			addCriterion("deviceMetaId between", value1, value2, "devicemetaid");
			return this;
		}

		public Criteria andDevicemetaidNotBetween(Integer value1, Integer value2) {
			addCriterion("deviceMetaId not between", value1, value2,
					"devicemetaid");
			return this;
		}

		public Criteria andDeviceentityidIsNull() {
			addCriterion("deviceEntityId is null");
			return this;
		}

		public Criteria andDeviceentityidIsNotNull() {
			addCriterion("deviceEntityId is not null");
			return this;
		}

		public Criteria andDeviceentityidEqualTo(String value) {
			addCriterion("deviceEntityId =", value, "deviceentityid");
			return this;
		}

		public Criteria andDeviceentityidNotEqualTo(String value) {
			addCriterion("deviceEntityId <>", value, "deviceentityid");
			return this;
		}

		public Criteria andDeviceentityidGreaterThan(String value) {
			addCriterion("deviceEntityId >", value, "deviceentityid");
			return this;
		}

		public Criteria andDeviceentityidGreaterThanOrEqualTo(String value) {
			addCriterion("deviceEntityId >=", value, "deviceentityid");
			return this;
		}

		public Criteria andDeviceentityidLessThan(String value) {
			addCriterion("deviceEntityId <", value, "deviceentityid");
			return this;
		}

		public Criteria andDeviceentityidLessThanOrEqualTo(String value) {
			addCriterion("deviceEntityId <=", value, "deviceentityid");
			return this;
		}

		public Criteria andDeviceentityidLike(String value) {
			addCriterion("deviceEntityId like", value, "deviceentityid");
			return this;
		}

		public Criteria andDeviceentityidNotLike(String value) {
			addCriterion("deviceEntityId not like", value, "deviceentityid");
			return this;
		}

		public Criteria andDeviceentityidIn(List values) {
			addCriterion("deviceEntityId in", values, "deviceentityid");
			return this;
		}

		public Criteria andDeviceentityidNotIn(List values) {
			addCriterion("deviceEntityId not in", values, "deviceentityid");
			return this;
		}

		public Criteria andDeviceentityidBetween(String value1, String value2) {
			addCriterion("deviceEntityId between", value1, value2,
					"deviceentityid");
			return this;
		}

		public Criteria andDeviceentityidNotBetween(String value1, String value2) {
			addCriterion("deviceEntityId not between", value1, value2,
					"deviceentityid");
			return this;
		}

		public Criteria andDeviceentitycodeIsNull() {
			addCriterion("deviceEntityCode is null");
			return this;
		}

		public Criteria andDeviceentitycodeIsNotNull() {
			addCriterion("deviceEntityCode is not null");
			return this;
		}

		public Criteria andDeviceentitycodeEqualTo(String value) {
			addCriterion("deviceEntityCode =", value, "deviceentitycode");
			return this;
		}

		public Criteria andDeviceentitycodeNotEqualTo(String value) {
			addCriterion("deviceEntityCode <>", value, "deviceentitycode");
			return this;
		}

		public Criteria andDeviceentitycodeGreaterThan(String value) {
			addCriterion("deviceEntityCode >", value, "deviceentitycode");
			return this;
		}

		public Criteria andDeviceentitycodeGreaterThanOrEqualTo(String value) {
			addCriterion("deviceEntityCode >=", value, "deviceentitycode");
			return this;
		}

		public Criteria andDeviceentitycodeLessThan(String value) {
			addCriterion("deviceEntityCode <", value, "deviceentitycode");
			return this;
		}

		public Criteria andDeviceentitycodeLessThanOrEqualTo(String value) {
			addCriterion("deviceEntityCode <=", value, "deviceentitycode");
			return this;
		}

		public Criteria andDeviceentitycodeLike(String value) {
			addCriterion("deviceEntityCode like", value, "deviceentitycode");
			return this;
		}

		public Criteria andDeviceentitycodeNotLike(String value) {
			addCriterion("deviceEntityCode not like", value, "deviceentitycode");
			return this;
		}

		public Criteria andDeviceentitycodeIn(List values) {
			addCriterion("deviceEntityCode in", values, "deviceentitycode");
			return this;
		}

		public Criteria andDeviceentitycodeNotIn(List values) {
			addCriterion("deviceEntityCode not in", values, "deviceentitycode");
			return this;
		}

		public Criteria andDeviceentitycodeBetween(String value1, String value2) {
			addCriterion("deviceEntityCode between", value1, value2,
					"deviceentitycode");
			return this;
		}

		public Criteria andDeviceentitycodeNotBetween(String value1,
				String value2) {
			addCriterion("deviceEntityCode not between", value1, value2,
					"deviceentitycode");
			return this;
		}

		public Criteria andDeviceentitynameIsNull() {
			addCriterion("deviceEntityName is null");
			return this;
		}

		public Criteria andDeviceentitynameIsNotNull() {
			addCriterion("deviceEntityName is not null");
			return this;
		}

		public Criteria andDeviceentitynameEqualTo(String value) {
			addCriterion("deviceEntityName =", value, "deviceentityname");
			return this;
		}

		public Criteria andDeviceentitynameNotEqualTo(String value) {
			addCriterion("deviceEntityName <>", value, "deviceentityname");
			return this;
		}

		public Criteria andDeviceentitynameGreaterThan(String value) {
			addCriterion("deviceEntityName >", value, "deviceentityname");
			return this;
		}

		public Criteria andDeviceentitynameGreaterThanOrEqualTo(String value) {
			addCriterion("deviceEntityName >=", value, "deviceentityname");
			return this;
		}

		public Criteria andDeviceentitynameLessThan(String value) {
			addCriterion("deviceEntityName <", value, "deviceentityname");
			return this;
		}

		public Criteria andDeviceentitynameLessThanOrEqualTo(String value) {
			addCriterion("deviceEntityName <=", value, "deviceentityname");
			return this;
		}

		public Criteria andDeviceentitynameLike(String value) {
			addCriterion("deviceEntityName like", value, "deviceentityname");
			return this;
		}

		public Criteria andDeviceentitynameNotLike(String value) {
			addCriterion("deviceEntityName not like", value, "deviceentityname");
			return this;
		}

		public Criteria andDeviceentitynameIn(List values) {
			addCriterion("deviceEntityName in", values, "deviceentityname");
			return this;
		}

		public Criteria andDeviceentitynameNotIn(List values) {
			addCriterion("deviceEntityName not in", values, "deviceentityname");
			return this;
		}

		public Criteria andDeviceentitynameBetween(String value1, String value2) {
			addCriterion("deviceEntityName between", value1, value2,
					"deviceentityname");
			return this;
		}

		public Criteria andDeviceentitynameNotBetween(String value1,
				String value2) {
			addCriterion("deviceEntityName not between", value1, value2,
					"deviceentityname");
			return this;
		}

		public Criteria andSparepartsidIsNull() {
			addCriterion("sparePartsId is null");
			return this;
		}

		public Criteria andSparepartsidIsNotNull() {
			addCriterion("sparePartsId is not null");
			return this;
		}

		public Criteria andSparepartsidEqualTo(String value) {
			addCriterion("sparePartsId =", value, "sparepartsid");
			return this;
		}

		public Criteria andSparepartsidNotEqualTo(String value) {
			addCriterion("sparePartsId <>", value, "sparepartsid");
			return this;
		}

		public Criteria andSparepartsidGreaterThan(String value) {
			addCriterion("sparePartsId >", value, "sparepartsid");
			return this;
		}

		public Criteria andSparepartsidGreaterThanOrEqualTo(String value) {
			addCriterion("sparePartsId >=", value, "sparepartsid");
			return this;
		}

		public Criteria andSparepartsidLessThan(String value) {
			addCriterion("sparePartsId <", value, "sparepartsid");
			return this;
		}

		public Criteria andSparepartsidLessThanOrEqualTo(String value) {
			addCriterion("sparePartsId <=", value, "sparepartsid");
			return this;
		}

		public Criteria andSparepartsidLike(String value) {
			addCriterion("sparePartsId like", value, "sparepartsid");
			return this;
		}

		public Criteria andSparepartsidNotLike(String value) {
			addCriterion("sparePartsId not like", value, "sparepartsid");
			return this;
		}

		public Criteria andSparepartsidIn(List values) {
			addCriterion("sparePartsId in", values, "sparepartsid");
			return this;
		}

		public Criteria andSparepartsidNotIn(List values) {
			addCriterion("sparePartsId not in", values, "sparepartsid");
			return this;
		}

		public Criteria andSparepartsidBetween(String value1, String value2) {
			addCriterion("sparePartsId between", value1, value2, "sparepartsid");
			return this;
		}

		public Criteria andSparepartsidNotBetween(String value1, String value2) {
			addCriterion("sparePartsId not between", value1, value2,
					"sparepartsid");
			return this;
		}

		public Criteria andSparepartscodeIsNull() {
			addCriterion("sparePartsCode is null");
			return this;
		}

		public Criteria andSparepartscodeIsNotNull() {
			addCriterion("sparePartsCode is not null");
			return this;
		}

		public Criteria andSparepartscodeEqualTo(String value) {
			addCriterion("sparePartsCode =", value, "sparepartscode");
			return this;
		}

		public Criteria andSparepartscodeNotEqualTo(String value) {
			addCriterion("sparePartsCode <>", value, "sparepartscode");
			return this;
		}

		public Criteria andSparepartscodeGreaterThan(String value) {
			addCriterion("sparePartsCode >", value, "sparepartscode");
			return this;
		}

		public Criteria andSparepartscodeGreaterThanOrEqualTo(String value) {
			addCriterion("sparePartsCode >=", value, "sparepartscode");
			return this;
		}

		public Criteria andSparepartscodeLessThan(String value) {
			addCriterion("sparePartsCode <", value, "sparepartscode");
			return this;
		}

		public Criteria andSparepartscodeLessThanOrEqualTo(String value) {
			addCriterion("sparePartsCode <=", value, "sparepartscode");
			return this;
		}

		public Criteria andSparepartscodeLike(String value) {
			addCriterion("sparePartsCode like", value, "sparepartscode");
			return this;
		}

		public Criteria andSparepartscodeNotLike(String value) {
			addCriterion("sparePartsCode not like", value, "sparepartscode");
			return this;
		}

		public Criteria andSparepartscodeIn(List values) {
			addCriterion("sparePartsCode in", values, "sparepartscode");
			return this;
		}

		public Criteria andSparepartscodeNotIn(List values) {
			addCriterion("sparePartsCode not in", values, "sparepartscode");
			return this;
		}

		public Criteria andSparepartscodeBetween(String value1, String value2) {
			addCriterion("sparePartsCode between", value1, value2,
					"sparepartscode");
			return this;
		}

		public Criteria andSparepartscodeNotBetween(String value1, String value2) {
			addCriterion("sparePartsCode not between", value1, value2,
					"sparepartscode");
			return this;
		}

		public Criteria andSparepartsnameIsNull() {
			addCriterion("sparePartsName is null");
			return this;
		}

		public Criteria andSparepartsnameIsNotNull() {
			addCriterion("sparePartsName is not null");
			return this;
		}

		public Criteria andSparepartsnameEqualTo(String value) {
			addCriterion("sparePartsName =", value, "sparepartsname");
			return this;
		}

		public Criteria andSparepartsnameNotEqualTo(String value) {
			addCriterion("sparePartsName <>", value, "sparepartsname");
			return this;
		}

		public Criteria andSparepartsnameGreaterThan(String value) {
			addCriterion("sparePartsName >", value, "sparepartsname");
			return this;
		}

		public Criteria andSparepartsnameGreaterThanOrEqualTo(String value) {
			addCriterion("sparePartsName >=", value, "sparepartsname");
			return this;
		}

		public Criteria andSparepartsnameLessThan(String value) {
			addCriterion("sparePartsName <", value, "sparepartsname");
			return this;
		}

		public Criteria andSparepartsnameLessThanOrEqualTo(String value) {
			addCriterion("sparePartsName <=", value, "sparepartsname");
			return this;
		}

		public Criteria andSparepartsnameLike(String value) {
			addCriterion("sparePartsName like", value, "sparepartsname");
			return this;
		}

		public Criteria andSparepartsnameNotLike(String value) {
			addCriterion("sparePartsName not like", value, "sparepartsname");
			return this;
		}

		public Criteria andSparepartsnameIn(List values) {
			addCriterion("sparePartsName in", values, "sparepartsname");
			return this;
		}

		public Criteria andSparepartsnameNotIn(List values) {
			addCriterion("sparePartsName not in", values, "sparepartsname");
			return this;
		}

		public Criteria andSparepartsnameBetween(String value1, String value2) {
			addCriterion("sparePartsName between", value1, value2,
					"sparepartsname");
			return this;
		}

		public Criteria andSparepartsnameNotBetween(String value1, String value2) {
			addCriterion("sparePartsName not between", value1, value2,
					"sparepartsname");
			return this;
		}

		public Criteria andDesignlifeIsNull() {
			addCriterion("designLife is null");
			return this;
		}

		public Criteria andDesignlifeIsNotNull() {
			addCriterion("designLife is not null");
			return this;
		}

		public Criteria andDesignlifeEqualTo(String value) {
			addCriterion("designLife =", value, "designlife");
			return this;
		}

		public Criteria andDesignlifeNotEqualTo(String value) {
			addCriterion("designLife <>", value, "designlife");
			return this;
		}

		public Criteria andDesignlifeGreaterThan(String value) {
			addCriterion("designLife >", value, "designlife");
			return this;
		}

		public Criteria andDesignlifeGreaterThanOrEqualTo(String value) {
			addCriterion("designLife >=", value, "designlife");
			return this;
		}

		public Criteria andDesignlifeLessThan(String value) {
			addCriterion("designLife <", value, "designlife");
			return this;
		}

		public Criteria andDesignlifeLessThanOrEqualTo(String value) {
			addCriterion("designLife <=", value, "designlife");
			return this;
		}

		public Criteria andDesignlifeLike(String value) {
			addCriterion("designLife like", value, "designlife");
			return this;
		}

		public Criteria andDesignlifeNotLike(String value) {
			addCriterion("designLife not like", value, "designlife");
			return this;
		}

		public Criteria andDesignlifeIn(List values) {
			addCriterion("designLife in", values, "designlife");
			return this;
		}

		public Criteria andDesignlifeNotIn(List values) {
			addCriterion("designLife not in", values, "designlife");
			return this;
		}

		public Criteria andDesignlifeBetween(String value1, String value2) {
			addCriterion("designLife between", value1, value2, "designlife");
			return this;
		}

		public Criteria andDesignlifeNotBetween(String value1, String value2) {
			addCriterion("designLife not between", value1, value2, "designlife");
			return this;
		}

		public Criteria andWorklifeIsNull() {
			addCriterion("workLife is null");
			return this;
		}

		public Criteria andWorklifeIsNotNull() {
			addCriterion("workLife is not null");
			return this;
		}

		public Criteria andWorklifeEqualTo(String value) {
			addCriterion("workLife =", value, "worklife");
			return this;
		}

		public Criteria andWorklifeNotEqualTo(String value) {
			addCriterion("workLife <>", value, "worklife");
			return this;
		}

		public Criteria andWorklifeGreaterThan(String value) {
			addCriterion("workLife >", value, "worklife");
			return this;
		}

		public Criteria andWorklifeGreaterThanOrEqualTo(String value) {
			addCriterion("workLife >=", value, "worklife");
			return this;
		}

		public Criteria andWorklifeLessThan(String value) {
			addCriterion("workLife <", value, "worklife");
			return this;
		}

		public Criteria andWorklifeLessThanOrEqualTo(String value) {
			addCriterion("workLife <=", value, "worklife");
			return this;
		}

		public Criteria andWorklifeLike(String value) {
			addCriterion("workLife like", value, "worklife");
			return this;
		}

		public Criteria andWorklifeNotLike(String value) {
			addCriterion("workLife not like", value, "worklife");
			return this;
		}

		public Criteria andWorklifeIn(List values) {
			addCriterion("workLife in", values, "worklife");
			return this;
		}

		public Criteria andWorklifeNotIn(List values) {
			addCriterion("workLife not in", values, "worklife");
			return this;
		}

		public Criteria andWorklifeBetween(String value1, String value2) {
			addCriterion("workLife between", value1, value2, "worklife");
			return this;
		}

		public Criteria andWorklifeNotBetween(String value1, String value2) {
			addCriterion("workLife not between", value1, value2, "worklife");
			return this;
		}

		public Criteria andWorkpercentIsNull() {
			addCriterion("workPercent is null");
			return this;
		}

		public Criteria andWorkpercentIsNotNull() {
			addCriterion("workPercent is not null");
			return this;
		}

		public Criteria andWorkpercentEqualTo(String value) {
			addCriterion("workPercent =", value, "workpercent");
			return this;
		}

		public Criteria andWorkpercentNotEqualTo(String value) {
			addCriterion("workPercent <>", value, "workpercent");
			return this;
		}

		public Criteria andWorkpercentGreaterThan(String value) {
			addCriterion("workPercent >", value, "workpercent");
			return this;
		}

		public Criteria andWorkpercentGreaterThanOrEqualTo(String value) {
			addCriterion("workPercent >=", value, "workpercent");
			return this;
		}

		public Criteria andWorkpercentLessThan(String value) {
			addCriterion("workPercent <", value, "workpercent");
			return this;
		}

		public Criteria andWorkpercentLessThanOrEqualTo(String value) {
			addCriterion("workPercent <=", value, "workpercent");
			return this;
		}

		public Criteria andWorkpercentLike(String value) {
			addCriterion("workPercent like", value, "workpercent");
			return this;
		}

		public Criteria andWorkpercentNotLike(String value) {
			addCriterion("workPercent not like", value, "workpercent");
			return this;
		}

		public Criteria andWorkpercentIn(List values) {
			addCriterion("workPercent in", values, "workpercent");
			return this;
		}

		public Criteria andWorkpercentNotIn(List values) {
			addCriterion("workPercent not in", values, "workpercent");
			return this;
		}

		public Criteria andWorkpercentBetween(String value1, String value2) {
			addCriterion("workPercent between", value1, value2, "workpercent");
			return this;
		}

		public Criteria andWorkpercentNotBetween(String value1, String value2) {
			addCriterion("workPercent not between", value1, value2,
					"workpercent");
			return this;
		}
	}
}