package com.changan.app.report.model;

public class TSparepartsAlarm {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_spareparts_alarm.id
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_spareparts_alarm.deviceMetaId
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	private Integer devicemetaid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_spareparts_alarm.deviceEntityId
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	private String deviceentityid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_spareparts_alarm.deviceEntityCode
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	private String deviceentitycode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_spareparts_alarm.deviceEntityName
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	private String deviceentityname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_spareparts_alarm.sparePartsId
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	private String sparepartsid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_spareparts_alarm.sparePartsCode
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	private String sparepartscode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_spareparts_alarm.sparePartsName
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	private String sparepartsname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_spareparts_alarm.designLife
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	private String designlife;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_spareparts_alarm.workLife
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	private String worklife;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_spareparts_alarm.workPercent
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	private String workpercent;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_spareparts_alarm.id
	 * @return  the value of t_spareparts_alarm.id
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_spareparts_alarm.id
	 * @param id  the value for t_spareparts_alarm.id
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_spareparts_alarm.deviceMetaId
	 * @return  the value of t_spareparts_alarm.deviceMetaId
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public Integer getDevicemetaid() {
		return devicemetaid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_spareparts_alarm.deviceMetaId
	 * @param devicemetaid  the value for t_spareparts_alarm.deviceMetaId
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public void setDevicemetaid(Integer devicemetaid) {
		this.devicemetaid = devicemetaid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_spareparts_alarm.deviceEntityId
	 * @return  the value of t_spareparts_alarm.deviceEntityId
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public String getDeviceentityid() {
		return deviceentityid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_spareparts_alarm.deviceEntityId
	 * @param deviceentityid  the value for t_spareparts_alarm.deviceEntityId
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public void setDeviceentityid(String deviceentityid) {
		this.deviceentityid = deviceentityid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_spareparts_alarm.deviceEntityCode
	 * @return  the value of t_spareparts_alarm.deviceEntityCode
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public String getDeviceentitycode() {
		return deviceentitycode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_spareparts_alarm.deviceEntityCode
	 * @param deviceentitycode  the value for t_spareparts_alarm.deviceEntityCode
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public void setDeviceentitycode(String deviceentitycode) {
		this.deviceentitycode = deviceentitycode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_spareparts_alarm.deviceEntityName
	 * @return  the value of t_spareparts_alarm.deviceEntityName
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public String getDeviceentityname() {
		return deviceentityname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_spareparts_alarm.deviceEntityName
	 * @param deviceentityname  the value for t_spareparts_alarm.deviceEntityName
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public void setDeviceentityname(String deviceentityname) {
		this.deviceentityname = deviceentityname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_spareparts_alarm.sparePartsId
	 * @return  the value of t_spareparts_alarm.sparePartsId
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public String getSparepartsid() {
		return sparepartsid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_spareparts_alarm.sparePartsId
	 * @param sparepartsid  the value for t_spareparts_alarm.sparePartsId
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public void setSparepartsid(String sparepartsid) {
		this.sparepartsid = sparepartsid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_spareparts_alarm.sparePartsCode
	 * @return  the value of t_spareparts_alarm.sparePartsCode
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public String getSparepartscode() {
		return sparepartscode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_spareparts_alarm.sparePartsCode
	 * @param sparepartscode  the value for t_spareparts_alarm.sparePartsCode
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public void setSparepartscode(String sparepartscode) {
		this.sparepartscode = sparepartscode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_spareparts_alarm.sparePartsName
	 * @return  the value of t_spareparts_alarm.sparePartsName
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public String getSparepartsname() {
		return sparepartsname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_spareparts_alarm.sparePartsName
	 * @param sparepartsname  the value for t_spareparts_alarm.sparePartsName
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public void setSparepartsname(String sparepartsname) {
		this.sparepartsname = sparepartsname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_spareparts_alarm.designLife
	 * @return  the value of t_spareparts_alarm.designLife
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public String getDesignlife() {
		return designlife;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_spareparts_alarm.designLife
	 * @param designlife  the value for t_spareparts_alarm.designLife
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public void setDesignlife(String designlife) {
		this.designlife = designlife;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_spareparts_alarm.workLife
	 * @return  the value of t_spareparts_alarm.workLife
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public String getWorklife() {
		return worklife;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_spareparts_alarm.workLife
	 * @param worklife  the value for t_spareparts_alarm.workLife
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public void setWorklife(String worklife) {
		this.worklife = worklife;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_spareparts_alarm.workPercent
	 * @return  the value of t_spareparts_alarm.workPercent
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public String getWorkpercent() {
		return workpercent;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_spareparts_alarm.workPercent
	 * @param workpercent  the value for t_spareparts_alarm.workPercent
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public void setWorkpercent(String workpercent) {
		this.workpercent = workpercent;
	}
}