package com.changan.app.report.dao;

import com.changan.app.report.model.TSparepartsAlarm;
import com.changan.app.report.model.TSparepartsAlarmExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TSparepartsAlarmDAOImpl extends SqlMapClientDaoSupport implements TSparepartsAlarmDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public TSparepartsAlarmDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public void insert(TSparepartsAlarm record) {
		getSqlMapClientTemplate().insert(
				"t_spareparts_alarm.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public int updateByPrimaryKey(TSparepartsAlarm record) {
		int rows = getSqlMapClientTemplate()
				.update("t_spareparts_alarm.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public int updateByPrimaryKeySelective(TSparepartsAlarm record) {
		int rows = getSqlMapClientTemplate()
				.update("t_spareparts_alarm.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public List selectByExample(TSparepartsAlarmExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_spareparts_alarm.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public TSparepartsAlarm selectByPrimaryKey(String id) {
		TSparepartsAlarm key = new TSparepartsAlarm();
		key.setId(id);
		TSparepartsAlarm record = (TSparepartsAlarm) getSqlMapClientTemplate()
				.queryForObject(
						"t_spareparts_alarm.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public int deleteByExample(TSparepartsAlarmExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_spareparts_alarm.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public int deleteByPrimaryKey(String id) {
		TSparepartsAlarm key = new TSparepartsAlarm();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"t_spareparts_alarm.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public int countByExample(TSparepartsAlarmExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_spareparts_alarm.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public int updateByExampleSelective(TSparepartsAlarm record,
			TSparepartsAlarmExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_spareparts_alarm.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	public int updateByExample(TSparepartsAlarm record,
			TSparepartsAlarmExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_spareparts_alarm.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	private static class UpdateByExampleParms extends TSparepartsAlarmExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				TSparepartsAlarmExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}