package com.changan.app.report.dao;

import com.changan.app.report.model.TSparepartsAlarm;
import com.changan.app.report.model.TSparepartsAlarmExample;
import java.util.List;

public interface TSparepartsAlarmDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	void insert(TSparepartsAlarm record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	int updateByPrimaryKey(TSparepartsAlarm record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	int updateByPrimaryKeySelective(TSparepartsAlarm record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	List selectByExample(TSparepartsAlarmExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	TSparepartsAlarm selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	int deleteByExample(TSparepartsAlarmExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	int countByExample(TSparepartsAlarmExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	int updateByExampleSelective(TSparepartsAlarm record,
			TSparepartsAlarmExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_spareparts_alarm
	 * @abatorgenerated  Sun Mar 13 22:22:43 CST 2016
	 */
	int updateByExample(TSparepartsAlarm record, TSparepartsAlarmExample example);
}