package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Cgcdevice104;
import com.changan.plcinterface.model.Cgcdevice104Example;
import java.util.List;

public interface Cgcdevice104DAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice104
     *
     * @abatorgenerated Wed Mar 02 09:19:44 CST 2016
     */
    void insert(Cgcdevice104 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice104
     *
     * @abatorgenerated Wed Mar 02 09:19:44 CST 2016
     */
    List selectByExample(Cgcdevice104Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice104
     *
     * @abatorgenerated Wed Mar 02 09:19:44 CST 2016
     */
    int deleteByExample(Cgcdevice104Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice104
     *
     * @abatorgenerated Wed Mar 02 09:19:44 CST 2016
     */
    int countByExample(Cgcdevice104Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice104
     *
     * @abatorgenerated Wed Mar 02 09:19:44 CST 2016
     */
    int updateByExampleSelective(Cgcdevice104 record, Cgcdevice104Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice104
     *
     * @abatorgenerated Wed Mar 02 09:19:44 CST 2016
     */
    int updateByExample(Cgcdevice104 record, Cgcdevice104Example example);
}