package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Cgcdevice;
import com.changan.plcinterface.model.CgcdeviceExample;
import com.changan.plcinterface.model.CgcdeviceKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CgcdeviceDAOImpl extends SqlMapClientDaoSupport implements CgcdeviceDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public CgcdeviceDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public void insert(Cgcdevice record) {
        getSqlMapClientTemplate().insert("cgcdevice.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public int updateByPrimaryKey(Cgcdevice record) {
        int rows = getSqlMapClientTemplate().update("cgcdevice.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public int updateByPrimaryKeySelective(Cgcdevice record) {
        int rows = getSqlMapClientTemplate().update("cgcdevice.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public List selectByExample(CgcdeviceExample example) {
        List list = getSqlMapClientTemplate().queryForList("cgcdevice.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public List selectByExamplePage(CgcdeviceExample example) {
        List list = getSqlMapClientTemplate().queryForList("cgcdevice.abatorgenerated_selectByExamplePage", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public Cgcdevice selectByPrimaryKey(CgcdeviceKey key) {
        Cgcdevice record = (Cgcdevice) getSqlMapClientTemplate().queryForObject("cgcdevice.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public int deleteByExample(CgcdeviceExample example) {
        int rows = getSqlMapClientTemplate().delete("cgcdevice.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public int deleteByPrimaryKey(CgcdeviceKey key) {
        int rows = getSqlMapClientTemplate().delete("cgcdevice.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public int countByExample(CgcdeviceExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("cgcdevice.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public int updateByExampleSelective(Cgcdevice record, CgcdeviceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cgcdevice.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    public int updateByExample(Cgcdevice record, CgcdeviceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cgcdevice.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    private static class UpdateByExampleParms extends CgcdeviceExample {
        private Object record;

        public UpdateByExampleParms(Object record, CgcdeviceExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}