package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Cgcdevice106;
import com.changan.plcinterface.model.Cgcdevice106Example;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Cgcdevice106DAOImpl extends SqlMapClientDaoSupport implements Cgcdevice106DAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice106
     *
     * @abatorgenerated Wed Mar 02 09:20:09 CST 2016
     */
    public Cgcdevice106DAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice106
     *
     * @abatorgenerated Wed Mar 02 09:20:09 CST 2016
     */
    public void insert(Cgcdevice106 record) {
        getSqlMapClientTemplate().insert("cgcdevice106.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice106
     *
     * @abatorgenerated Wed Mar 02 09:20:09 CST 2016
     */
    public List selectByExample(Cgcdevice106Example example) {
        List list = getSqlMapClientTemplate().queryForList("cgcdevice106.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice106
     *
     * @abatorgenerated Wed Mar 02 09:20:09 CST 2016
     */
    public int deleteByExample(Cgcdevice106Example example) {
        int rows = getSqlMapClientTemplate().delete("cgcdevice106.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice106
     *
     * @abatorgenerated Wed Mar 02 09:20:09 CST 2016
     */
    public int countByExample(Cgcdevice106Example example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("cgcdevice106.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice106
     *
     * @abatorgenerated Wed Mar 02 09:20:09 CST 2016
     */
    public int updateByExampleSelective(Cgcdevice106 record, Cgcdevice106Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cgcdevice106.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice106
     *
     * @abatorgenerated Wed Mar 02 09:20:09 CST 2016
     */
    public int updateByExample(Cgcdevice106 record, Cgcdevice106Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cgcdevice106.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table cgcdevice106
     *
     * @abatorgenerated Wed Mar 02 09:20:09 CST 2016
     */
    private static class UpdateByExampleParms extends Cgcdevice106Example {
        private Object record;

        public UpdateByExampleParms(Object record, Cgcdevice106Example example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}