package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Cgcdevice;
import com.changan.plcinterface.model.CgcdeviceExample;
import com.changan.plcinterface.model.CgcdeviceKey;
import java.util.List;

public interface CgcdeviceDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    void insert(Cgcdevice record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    int updateByPrimaryKey(Cgcdevice record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    int updateByPrimaryKeySelective(Cgcdevice record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    List selectByExample(CgcdeviceExample example);

    List selectByExamplePage(CgcdeviceExample example);
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    Cgcdevice selectByPrimaryKey(CgcdeviceKey key);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    int deleteByExample(CgcdeviceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    int deleteByPrimaryKey(CgcdeviceKey key);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    int countByExample(CgcdeviceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    int updateByExampleSelective(Cgcdevice record, CgcdeviceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice
     *
     * @abatorgenerated Fri Apr 15 21:28:55 CST 2016
     */
    int updateByExample(Cgcdevice record, CgcdeviceExample example);
}