package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Cgcdevice107;
import com.changan.plcinterface.model.Cgcdevice107Example;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Cgcdevice107DAOImpl extends SqlMapClientDaoSupport implements Cgcdevice107DAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice107
     *
     * @abatorgenerated Wed Mar 02 09:20:24 CST 2016
     */
    public Cgcdevice107DAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice107
     *
     * @abatorgenerated Wed Mar 02 09:20:24 CST 2016
     */
    public void insert(Cgcdevice107 record) {
        getSqlMapClientTemplate().insert("cgcdevice107.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice107
     *
     * @abatorgenerated Wed Mar 02 09:20:24 CST 2016
     */
    public List selectByExample(Cgcdevice107Example example) {
        List list = getSqlMapClientTemplate().queryForList("cgcdevice107.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice107
     *
     * @abatorgenerated Wed Mar 02 09:20:24 CST 2016
     */
    public int deleteByExample(Cgcdevice107Example example) {
        int rows = getSqlMapClientTemplate().delete("cgcdevice107.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice107
     *
     * @abatorgenerated Wed Mar 02 09:20:24 CST 2016
     */
    public int countByExample(Cgcdevice107Example example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("cgcdevice107.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice107
     *
     * @abatorgenerated Wed Mar 02 09:20:24 CST 2016
     */
    public int updateByExampleSelective(Cgcdevice107 record, Cgcdevice107Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cgcdevice107.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice107
     *
     * @abatorgenerated Wed Mar 02 09:20:24 CST 2016
     */
    public int updateByExample(Cgcdevice107 record, Cgcdevice107Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cgcdevice107.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table cgcdevice107
     *
     * @abatorgenerated Wed Mar 02 09:20:24 CST 2016
     */
    private static class UpdateByExampleParms extends Cgcdevice107Example {
        private Object record;

        public UpdateByExampleParms(Object record, Cgcdevice107Example example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}