package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Cgcdevice107;
import com.changan.plcinterface.model.Cgcdevice107Example;
import java.util.List;

public interface Cgcdevice107DAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice107
     *
     * @abatorgenerated Wed Mar 02 09:20:24 CST 2016
     */
    void insert(Cgcdevice107 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice107
     *
     * @abatorgenerated Wed Mar 02 09:20:24 CST 2016
     */
    List selectByExample(Cgcdevice107Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice107
     *
     * @abatorgenerated Wed Mar 02 09:20:24 CST 2016
     */
    int deleteByExample(Cgcdevice107Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice107
     *
     * @abatorgenerated Wed Mar 02 09:20:24 CST 2016
     */
    int countByExample(Cgcdevice107Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice107
     *
     * @abatorgenerated Wed Mar 02 09:20:24 CST 2016
     */
    int updateByExampleSelective(Cgcdevice107 record, Cgcdevice107Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice107
     *
     * @abatorgenerated Wed Mar 02 09:20:24 CST 2016
     */
    int updateByExample(Cgcdevice107 record, Cgcdevice107Example example);
}