package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Cgcdevice105;
import com.changan.plcinterface.model.Cgcdevice105Example;
import java.util.List;

public interface Cgcdevice105DAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice105
     *
     * @abatorgenerated Wed Mar 02 09:19:59 CST 2016
     */
    void insert(Cgcdevice105 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice105
     *
     * @abatorgenerated Wed Mar 02 09:19:59 CST 2016
     */
    List selectByExample(Cgcdevice105Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice105
     *
     * @abatorgenerated Wed Mar 02 09:19:59 CST 2016
     */
    int deleteByExample(Cgcdevice105Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice105
     *
     * @abatorgenerated Wed Mar 02 09:19:59 CST 2016
     */
    int countByExample(Cgcdevice105Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice105
     *
     * @abatorgenerated Wed Mar 02 09:19:59 CST 2016
     */
    int updateByExampleSelective(Cgcdevice105 record, Cgcdevice105Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice105
     *
     * @abatorgenerated Wed Mar 02 09:19:59 CST 2016
     */
    int updateByExample(Cgcdevice105 record, Cgcdevice105Example example);
}