package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Cgcdevice105;
import com.changan.plcinterface.model.Cgcdevice105Example;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Cgcdevice105DAOImpl extends SqlMapClientDaoSupport implements Cgcdevice105DAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice105
     *
     * @abatorgenerated Wed Mar 02 09:19:59 CST 2016
     */
    public Cgcdevice105DAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice105
     *
     * @abatorgenerated Wed Mar 02 09:19:59 CST 2016
     */
    public void insert(Cgcdevice105 record) {
        getSqlMapClientTemplate().insert("cgcdevice105.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice105
     *
     * @abatorgenerated Wed Mar 02 09:19:59 CST 2016
     */
    public List selectByExample(Cgcdevice105Example example) {
        List list = getSqlMapClientTemplate().queryForList("cgcdevice105.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice105
     *
     * @abatorgenerated Wed Mar 02 09:19:59 CST 2016
     */
    public int deleteByExample(Cgcdevice105Example example) {
        int rows = getSqlMapClientTemplate().delete("cgcdevice105.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice105
     *
     * @abatorgenerated Wed Mar 02 09:19:59 CST 2016
     */
    public int countByExample(Cgcdevice105Example example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("cgcdevice105.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice105
     *
     * @abatorgenerated Wed Mar 02 09:19:59 CST 2016
     */
    public int updateByExampleSelective(Cgcdevice105 record, Cgcdevice105Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cgcdevice105.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice105
     *
     * @abatorgenerated Wed Mar 02 09:19:59 CST 2016
     */
    public int updateByExample(Cgcdevice105 record, Cgcdevice105Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cgcdevice105.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table cgcdevice105
     *
     * @abatorgenerated Wed Mar 02 09:19:59 CST 2016
     */
    private static class UpdateByExampleParms extends Cgcdevice105Example {
        private Object record;

        public UpdateByExampleParms(Object record, Cgcdevice105Example example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}