package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Cgcdevice104;
import com.changan.plcinterface.model.Cgcdevice104Example;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Cgcdevice104DAOImpl extends SqlMapClientDaoSupport implements Cgcdevice104DAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice104
     *
     * @abatorgenerated Wed Mar 02 09:19:44 CST 2016
     */
    public Cgcdevice104DAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice104
     *
     * @abatorgenerated Wed Mar 02 09:19:44 CST 2016
     */
    public void insert(Cgcdevice104 record) {
        getSqlMapClientTemplate().insert("cgcdevice104.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice104
     *
     * @abatorgenerated Wed Mar 02 09:19:44 CST 2016
     */
    public List selectByExample(Cgcdevice104Example example) {
        List list = getSqlMapClientTemplate().queryForList("cgcdevice104.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice104
     *
     * @abatorgenerated Wed Mar 02 09:19:44 CST 2016
     */
    public int deleteByExample(Cgcdevice104Example example) {
        int rows = getSqlMapClientTemplate().delete("cgcdevice104.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice104
     *
     * @abatorgenerated Wed Mar 02 09:19:44 CST 2016
     */
    public int countByExample(Cgcdevice104Example example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("cgcdevice104.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice104
     *
     * @abatorgenerated Wed Mar 02 09:19:44 CST 2016
     */
    public int updateByExampleSelective(Cgcdevice104 record, Cgcdevice104Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cgcdevice104.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice104
     *
     * @abatorgenerated Wed Mar 02 09:19:44 CST 2016
     */
    public int updateByExample(Cgcdevice104 record, Cgcdevice104Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cgcdevice104.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table cgcdevice104
     *
     * @abatorgenerated Wed Mar 02 09:19:44 CST 2016
     */
    private static class UpdateByExampleParms extends Cgcdevice104Example {
        private Object record;

        public UpdateByExampleParms(Object record, Cgcdevice104Example example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}