package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Cgcdevice106;
import com.changan.plcinterface.model.Cgcdevice106Example;
import java.util.List;

public interface Cgcdevice106DAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice106
     *
     * @abatorgenerated Wed Mar 02 09:20:09 CST 2016
     */
    void insert(Cgcdevice106 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice106
     *
     * @abatorgenerated Wed Mar 02 09:20:09 CST 2016
     */
    List selectByExample(Cgcdevice106Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice106
     *
     * @abatorgenerated Wed Mar 02 09:20:09 CST 2016
     */
    int deleteByExample(Cgcdevice106Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice106
     *
     * @abatorgenerated Wed Mar 02 09:20:09 CST 2016
     */
    int countByExample(Cgcdevice106Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice106
     *
     * @abatorgenerated Wed Mar 02 09:20:09 CST 2016
     */
    int updateByExampleSelective(Cgcdevice106 record, Cgcdevice106Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table cgcdevice106
     *
     * @abatorgenerated Wed Mar 02 09:20:09 CST 2016
     */
    int updateByExample(Cgcdevice106 record, Cgcdevice106Example example);
}