package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Machinedevice103;
import com.changan.plcinterface.model.Machinedevice103Example;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Machinedevice103DAOImpl extends SqlMapClientDaoSupport implements Machinedevice103DAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    public Machinedevice103DAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    public void insert(Machinedevice103 record) {
        getSqlMapClientTemplate().insert("machinedevice103.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    public int updateByPrimaryKey(Machinedevice103 record) {
        int rows = getSqlMapClientTemplate().update("machinedevice103.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    public int updateByPrimaryKeySelective(Machinedevice103 record) {
        int rows = getSqlMapClientTemplate().update("machinedevice103.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    public List selectByExample(Machinedevice103Example example) {
        List list = getSqlMapClientTemplate().queryForList("machinedevice103.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    public Machinedevice103 selectByPrimaryKey(Long wprecordvalue) {
        Machinedevice103 key = new Machinedevice103();
        key.setWprecordvalue(wprecordvalue);
        Machinedevice103 record = (Machinedevice103) getSqlMapClientTemplate().queryForObject("machinedevice103.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    public int deleteByExample(Machinedevice103Example example) {
        int rows = getSqlMapClientTemplate().delete("machinedevice103.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    public int deleteByPrimaryKey(Long wprecordvalue) {
        Machinedevice103 key = new Machinedevice103();
        key.setWprecordvalue(wprecordvalue);
        int rows = getSqlMapClientTemplate().delete("machinedevice103.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    public int countByExample(Machinedevice103Example example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("machinedevice103.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    public int updateByExampleSelective(Machinedevice103 record, Machinedevice103Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("machinedevice103.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    public int updateByExample(Machinedevice103 record, Machinedevice103Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("machinedevice103.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    private static class UpdateByExampleParms extends Machinedevice103Example {
        private Object record;

        public UpdateByExampleParms(Object record, Machinedevice103Example example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}