package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Machinedevice102;
import com.changan.plcinterface.model.Machinedevice102Example;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Machinedevice102DAOImpl extends SqlMapClientDaoSupport implements Machinedevice102DAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    public Machinedevice102DAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    public void insert(Machinedevice102 record) {
        getSqlMapClientTemplate().insert("machinedevice102.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    public int updateByPrimaryKey(Machinedevice102 record) {
        int rows = getSqlMapClientTemplate().update("machinedevice102.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    public int updateByPrimaryKeySelective(Machinedevice102 record) {
        int rows = getSqlMapClientTemplate().update("machinedevice102.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    public List selectByExample(Machinedevice102Example example) {
        List list = getSqlMapClientTemplate().queryForList("machinedevice102.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    public Machinedevice102 selectByPrimaryKey(Long wprecordvalue) {
        Machinedevice102 key = new Machinedevice102();
        key.setWprecordvalue(wprecordvalue);
        Machinedevice102 record = (Machinedevice102) getSqlMapClientTemplate().queryForObject("machinedevice102.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    public int deleteByExample(Machinedevice102Example example) {
        int rows = getSqlMapClientTemplate().delete("machinedevice102.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    public int deleteByPrimaryKey(Long wprecordvalue) {
        Machinedevice102 key = new Machinedevice102();
        key.setWprecordvalue(wprecordvalue);
        int rows = getSqlMapClientTemplate().delete("machinedevice102.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    public int countByExample(Machinedevice102Example example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("machinedevice102.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    public int updateByExampleSelective(Machinedevice102 record, Machinedevice102Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("machinedevice102.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    public int updateByExample(Machinedevice102 record, Machinedevice102Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("machinedevice102.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    private static class UpdateByExampleParms extends Machinedevice102Example {
        private Object record;

        public UpdateByExampleParms(Object record, Machinedevice102Example example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}