package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Machinedevice102;
import com.changan.plcinterface.model.Machinedevice102Example;
import java.util.List;

public interface Machinedevice102DAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    void insert(Machinedevice102 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    int updateByPrimaryKey(Machinedevice102 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    int updateByPrimaryKeySelective(Machinedevice102 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    List selectByExample(Machinedevice102Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    Machinedevice102 selectByPrimaryKey(Long wprecordvalue);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    int deleteByExample(Machinedevice102Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    int deleteByPrimaryKey(Long wprecordvalue);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    int countByExample(Machinedevice102Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    int updateByExampleSelective(Machinedevice102 record, Machinedevice102Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice102
     *
     * @abatorgenerated Sat Feb 20 18:29:46 CST 2016
     */
    int updateByExample(Machinedevice102 record, Machinedevice102Example example);
}