package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Machinedevice103;
import com.changan.plcinterface.model.Machinedevice103Example;
import java.util.List;

public interface Machinedevice103DAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    void insert(Machinedevice103 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    int updateByPrimaryKey(Machinedevice103 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    int updateByPrimaryKeySelective(Machinedevice103 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    List selectByExample(Machinedevice103Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    Machinedevice103 selectByPrimaryKey(Long wprecordvalue);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    int deleteByExample(Machinedevice103Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    int deleteByPrimaryKey(Long wprecordvalue);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    int countByExample(Machinedevice103Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    int updateByExampleSelective(Machinedevice103 record, Machinedevice103Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice103
     *
     * @abatorgenerated Sat Feb 20 18:34:06 CST 2016
     */
    int updateByExample(Machinedevice103 record, Machinedevice103Example example);
}