package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Machinedevice;
import com.changan.plcinterface.model.MachinedeviceExample;
import com.changan.plcinterface.model.MachinedeviceKey;
import java.util.List;

public interface MachinedeviceDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    void insert(Machinedevice record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    int updateByPrimaryKey(Machinedevice record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    int updateByPrimaryKeySelective(Machinedevice record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    List selectByExample(MachinedeviceExample example);

    List selectByExamplePage(MachinedeviceExample example);
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    Machinedevice selectByPrimaryKey(MachinedeviceKey key);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    int deleteByExample(MachinedeviceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    int deleteByPrimaryKey(MachinedeviceKey key);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    int countByExample(MachinedeviceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    int updateByExampleSelective(Machinedevice record, MachinedeviceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table machinedevice
     *
     * @abatorgenerated Sat May 07 17:10:27 CST 2016
     */
    int updateByExample(Machinedevice record, MachinedeviceExample example);
}