package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Robotdevice102;
import com.changan.plcinterface.model.Robotdevice102Example;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Robotdevice102DAOImpl extends SqlMapClientDaoSupport implements Robotdevice102DAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	public Robotdevice102DAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	public void insert(Robotdevice102 record) {
		getSqlMapClientTemplate().insert(
				"robotdevice102.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	public int updateByPrimaryKey(Robotdevice102 record) {
		int rows = getSqlMapClientTemplate().update(
				"robotdevice102.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	public int updateByPrimaryKeySelective(Robotdevice102 record) {
		int rows = getSqlMapClientTemplate().update(
				"robotdevice102.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	public List selectByExample(Robotdevice102Example example) {
		List list = getSqlMapClientTemplate().queryForList(
				"robotdevice102.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	public Robotdevice102 selectByPrimaryKey(Long wprecordvalue) {
		Robotdevice102 key = new Robotdevice102();
		key.setWprecordvalue(wprecordvalue);
		Robotdevice102 record = (Robotdevice102) getSqlMapClientTemplate()
				.queryForObject(
						"robotdevice102.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	public int deleteByExample(Robotdevice102Example example) {
		int rows = getSqlMapClientTemplate().delete(
				"robotdevice102.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	public int deleteByPrimaryKey(Long wprecordvalue) {
		Robotdevice102 key = new Robotdevice102();
		key.setWprecordvalue(wprecordvalue);
		int rows = getSqlMapClientTemplate().delete(
				"robotdevice102.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	public int countByExample(Robotdevice102Example example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"robotdevice102.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	public int updateByExampleSelective(Robotdevice102 record,
			Robotdevice102Example example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"robotdevice102.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	public int updateByExample(Robotdevice102 record,
			Robotdevice102Example example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"robotdevice102.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	private static class UpdateByExampleParms extends Robotdevice102Example {
		private Object record;

		public UpdateByExampleParms(Object record, Robotdevice102Example example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}