package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Robotdevice102;
import com.changan.plcinterface.model.Robotdevice102Example;
import java.util.List;

public interface Robotdevice102DAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	void insert(Robotdevice102 record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	int updateByPrimaryKey(Robotdevice102 record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	int updateByPrimaryKeySelective(Robotdevice102 record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	List selectByExample(Robotdevice102Example example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	Robotdevice102 selectByPrimaryKey(Long wprecordvalue);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	int deleteByExample(Robotdevice102Example example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	int deleteByPrimaryKey(Long wprecordvalue);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	int countByExample(Robotdevice102Example example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	int updateByExampleSelective(Robotdevice102 record,
			Robotdevice102Example example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice102
	 * @abatorgenerated  Thu Jan 21 21:19:27 CST 2016
	 */
	int updateByExample(Robotdevice102 record, Robotdevice102Example example);
}