package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Robotdevice;
import com.changan.plcinterface.model.RobotdeviceExample;
import com.changan.plcinterface.model.RobotdeviceKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RobotdeviceDAOImpl extends SqlMapClientDaoSupport implements RobotdeviceDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table robotdevice
     *
     * @abatorgenerated Sat May 07 22:35:29 CST 2016
     */
    public RobotdeviceDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table robotdevice
     *
     * @abatorgenerated Sat May 07 22:35:29 CST 2016
     */
    public void insert(Robotdevice record) {
        getSqlMapClientTemplate().insert("robotdevice.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table robotdevice
     *
     * @abatorgenerated Sat May 07 22:35:29 CST 2016
     */
    public int updateByPrimaryKey(Robotdevice record) {
        int rows = getSqlMapClientTemplate().update("robotdevice.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table robotdevice
     *
     * @abatorgenerated Sat May 07 22:35:29 CST 2016
     */
    public int updateByPrimaryKeySelective(Robotdevice record) {
        int rows = getSqlMapClientTemplate().update("robotdevice.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table robotdevice
     *
     * @abatorgenerated Sat May 07 22:35:29 CST 2016
     */
    public List selectByExample(RobotdeviceExample example) {
        List list = getSqlMapClientTemplate().queryForList("robotdevice.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table robotdevice
     *
     * @abatorgenerated Sat May 07 22:35:29 CST 2016
     */
    public List selectByExamplePage(RobotdeviceExample example) {
        List list = getSqlMapClientTemplate().queryForList("robotdevice.abatorgenerated_selectByExamplePage", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table robotdevice
     *
     * @abatorgenerated Sat May 07 22:35:29 CST 2016
     */
    public Robotdevice selectByPrimaryKey(RobotdeviceKey key) {
        Robotdevice record = (Robotdevice) getSqlMapClientTemplate().queryForObject("robotdevice.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table robotdevice
     *
     * @abatorgenerated Sat May 07 22:35:29 CST 2016
     */
    public int deleteByExample(RobotdeviceExample example) {
        int rows = getSqlMapClientTemplate().delete("robotdevice.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table robotdevice
     *
     * @abatorgenerated Sat May 07 22:35:29 CST 2016
     */
    public int deleteByPrimaryKey(RobotdeviceKey key) {
        int rows = getSqlMapClientTemplate().delete("robotdevice.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table robotdevice
     *
     * @abatorgenerated Sat May 07 22:35:29 CST 2016
     */
    public int countByExample(RobotdeviceExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("robotdevice.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table robotdevice
     *
     * @abatorgenerated Sat May 07 22:35:29 CST 2016
     */
    public int updateByExampleSelective(Robotdevice record, RobotdeviceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("robotdevice.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table robotdevice
     *
     * @abatorgenerated Sat May 07 22:35:29 CST 2016
     */
    public int updateByExample(Robotdevice record, RobotdeviceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("robotdevice.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table robotdevice
     *
     * @abatorgenerated Sat May 07 22:35:29 CST 2016
     */
    private static class UpdateByExampleParms extends RobotdeviceExample {
        private Object record;

        public UpdateByExampleParms(Object record, RobotdeviceExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}