package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Robotdevice103;
import com.changan.plcinterface.model.Robotdevice103Example;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Robotdevice103DAOImpl extends SqlMapClientDaoSupport implements Robotdevice103DAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	public Robotdevice103DAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	public void insert(Robotdevice103 record) {
		getSqlMapClientTemplate().insert(
				"robotdevice103.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	public int updateByPrimaryKey(Robotdevice103 record) {
		int rows = getSqlMapClientTemplate().update(
				"robotdevice103.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	public int updateByPrimaryKeySelective(Robotdevice103 record) {
		int rows = getSqlMapClientTemplate().update(
				"robotdevice103.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	public List selectByExample(Robotdevice103Example example) {
		List list = getSqlMapClientTemplate().queryForList(
				"robotdevice103.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	public Robotdevice103 selectByPrimaryKey(Long wprecordvalue) {
		Robotdevice103 key = new Robotdevice103();
		key.setWprecordvalue(wprecordvalue);
		Robotdevice103 record = (Robotdevice103) getSqlMapClientTemplate()
				.queryForObject(
						"robotdevice103.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	public int deleteByExample(Robotdevice103Example example) {
		int rows = getSqlMapClientTemplate().delete(
				"robotdevice103.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	public int deleteByPrimaryKey(Long wprecordvalue) {
		Robotdevice103 key = new Robotdevice103();
		key.setWprecordvalue(wprecordvalue);
		int rows = getSqlMapClientTemplate().delete(
				"robotdevice103.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	public int countByExample(Robotdevice103Example example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"robotdevice103.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	public int updateByExampleSelective(Robotdevice103 record,
			Robotdevice103Example example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"robotdevice103.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	public int updateByExample(Robotdevice103 record,
			Robotdevice103Example example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"robotdevice103.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	private static class UpdateByExampleParms extends Robotdevice103Example {
		private Object record;

		public UpdateByExampleParms(Object record, Robotdevice103Example example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}