package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Robotdevice103;
import com.changan.plcinterface.model.Robotdevice103Example;
import java.util.List;

public interface Robotdevice103DAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	void insert(Robotdevice103 record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	int updateByPrimaryKey(Robotdevice103 record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	int updateByPrimaryKeySelective(Robotdevice103 record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	List selectByExample(Robotdevice103Example example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	Robotdevice103 selectByPrimaryKey(Long wprecordvalue);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	int deleteByExample(Robotdevice103Example example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	int deleteByPrimaryKey(Long wprecordvalue);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	int countByExample(Robotdevice103Example example);
	
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	int updateByExampleSelective(Robotdevice103 record,
			Robotdevice103Example example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table robotdevice103
	 * @abatorgenerated  Thu Jan 21 21:19:19 CST 2016
	 */
	int updateByExample(Robotdevice103 record, Robotdevice103Example example);
}