package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Shocksanddevice;
import com.changan.plcinterface.model.ShocksanddeviceExample;
import com.changan.plcinterface.model.ShocksanddeviceKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ShocksanddeviceDAOImpl extends SqlMapClientDaoSupport implements ShocksanddeviceDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shocksanddevice
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public ShocksanddeviceDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shocksanddevice
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public void insert(Shocksanddevice record) {
		getSqlMapClientTemplate().insert(
				"shocksanddevice.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shocksanddevice
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public int updateByPrimaryKey(Shocksanddevice record) {
		int rows = getSqlMapClientTemplate().update(
				"shocksanddevice.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shocksanddevice
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public int updateByPrimaryKeySelective(Shocksanddevice record) {
		int rows = getSqlMapClientTemplate().update(
				"shocksanddevice.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shocksanddevice
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public List selectByExample(ShocksanddeviceExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"shocksanddevice.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shocksanddevice
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public List selectByExamplePage(ShocksanddeviceExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"shocksanddevice.abatorgenerated_selectByExamplePage", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shocksanddevice
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public Shocksanddevice selectByPrimaryKey(ShocksanddeviceKey key) {
		Shocksanddevice record = (Shocksanddevice) getSqlMapClientTemplate()
				.queryForObject(
						"shocksanddevice.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shocksanddevice
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public int deleteByExample(ShocksanddeviceExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"shocksanddevice.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shocksanddevice
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public int deleteByPrimaryKey(ShocksanddeviceKey key) {
		int rows = getSqlMapClientTemplate().delete(
				"shocksanddevice.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shocksanddevice
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public int countByExample(ShocksanddeviceExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"shocksanddevice.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shocksanddevice
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public int updateByExampleSelective(Shocksanddevice record,
			ShocksanddeviceExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"shocksanddevice.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shocksanddevice
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	public int updateByExample(Shocksanddevice record,
			ShocksanddeviceExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"shocksanddevice.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table shocksanddevice
	 * @abatorgenerated  Sat May 07 23:28:29 CST 2016
	 */
	private static class UpdateByExampleParms extends ShocksanddeviceExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				ShocksanddeviceExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}