package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Shocksanddevice103;
import com.changan.plcinterface.model.Shocksanddevice103Example;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Shocksanddevice103DAOImpl extends SqlMapClientDaoSupport implements Shocksanddevice103DAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    public Shocksanddevice103DAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    public void insert(Shocksanddevice103 record) {
        getSqlMapClientTemplate().insert("shocksanddevice103.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    public int updateByPrimaryKey(Shocksanddevice103 record) {
        int rows = getSqlMapClientTemplate().update("shocksanddevice103.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    public int updateByPrimaryKeySelective(Shocksanddevice103 record) {
        int rows = getSqlMapClientTemplate().update("shocksanddevice103.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    public List selectByExample(Shocksanddevice103Example example) {
        List list = getSqlMapClientTemplate().queryForList("shocksanddevice103.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    public Shocksanddevice103 selectByPrimaryKey(Long wprecordvalue) {
        Shocksanddevice103 key = new Shocksanddevice103();
        key.setWprecordvalue(wprecordvalue);
        Shocksanddevice103 record = (Shocksanddevice103) getSqlMapClientTemplate().queryForObject("shocksanddevice103.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    public int deleteByExample(Shocksanddevice103Example example) {
        int rows = getSqlMapClientTemplate().delete("shocksanddevice103.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    public int deleteByPrimaryKey(Long wprecordvalue) {
        Shocksanddevice103 key = new Shocksanddevice103();
        key.setWprecordvalue(wprecordvalue);
        int rows = getSqlMapClientTemplate().delete("shocksanddevice103.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    public int countByExample(Shocksanddevice103Example example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("shocksanddevice103.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    public int updateByExampleSelective(Shocksanddevice103 record, Shocksanddevice103Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("shocksanddevice103.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    public int updateByExample(Shocksanddevice103 record, Shocksanddevice103Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("shocksanddevice103.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    private static class UpdateByExampleParms extends Shocksanddevice103Example {
        private Object record;

        public UpdateByExampleParms(Object record, Shocksanddevice103Example example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}