package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Shocksanddevice102;
import com.changan.plcinterface.model.Shocksanddevice102Example;
import java.util.List;

public interface Shocksanddevice102DAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    void insert(Shocksanddevice102 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    int updateByPrimaryKey(Shocksanddevice102 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    int updateByPrimaryKeySelective(Shocksanddevice102 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    List selectByExample(Shocksanddevice102Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    Shocksanddevice102 selectByPrimaryKey(Long wprecordvalue);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    int deleteByExample(Shocksanddevice102Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    int deleteByPrimaryKey(Long wprecordvalue);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    int countByExample(Shocksanddevice102Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    int updateByExampleSelective(Shocksanddevice102 record, Shocksanddevice102Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    int updateByExample(Shocksanddevice102 record, Shocksanddevice102Example example);
}