package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Shocksanddevice103;
import com.changan.plcinterface.model.Shocksanddevice103Example;
import java.util.List;

public interface Shocksanddevice103DAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    void insert(Shocksanddevice103 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    int updateByPrimaryKey(Shocksanddevice103 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    int updateByPrimaryKeySelective(Shocksanddevice103 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    List selectByExample(Shocksanddevice103Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    Shocksanddevice103 selectByPrimaryKey(Long wprecordvalue);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    int deleteByExample(Shocksanddevice103Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    int deleteByPrimaryKey(Long wprecordvalue);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    int countByExample(Shocksanddevice103Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    int updateByExampleSelective(Shocksanddevice103 record, Shocksanddevice103Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice103
     *
     * @abatorgenerated Tue Mar 01 11:47:01 CST 2016
     */
    int updateByExample(Shocksanddevice103 record, Shocksanddevice103Example example);
}