package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Shocksanddevice102;
import com.changan.plcinterface.model.Shocksanddevice102Example;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Shocksanddevice102DAOImpl extends SqlMapClientDaoSupport implements Shocksanddevice102DAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    public Shocksanddevice102DAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    public void insert(Shocksanddevice102 record) {
        getSqlMapClientTemplate().insert("shocksanddevice102.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    public int updateByPrimaryKey(Shocksanddevice102 record) {
        int rows = getSqlMapClientTemplate().update("shocksanddevice102.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    public int updateByPrimaryKeySelective(Shocksanddevice102 record) {
        int rows = getSqlMapClientTemplate().update("shocksanddevice102.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    public List selectByExample(Shocksanddevice102Example example) {
        List list = getSqlMapClientTemplate().queryForList("shocksanddevice102.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    public Shocksanddevice102 selectByPrimaryKey(Long wprecordvalue) {
        Shocksanddevice102 key = new Shocksanddevice102();
        key.setWprecordvalue(wprecordvalue);
        Shocksanddevice102 record = (Shocksanddevice102) getSqlMapClientTemplate().queryForObject("shocksanddevice102.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    public int deleteByExample(Shocksanddevice102Example example) {
        int rows = getSqlMapClientTemplate().delete("shocksanddevice102.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    public int deleteByPrimaryKey(Long wprecordvalue) {
        Shocksanddevice102 key = new Shocksanddevice102();
        key.setWprecordvalue(wprecordvalue);
        int rows = getSqlMapClientTemplate().delete("shocksanddevice102.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    public int countByExample(Shocksanddevice102Example example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("shocksanddevice102.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    public int updateByExampleSelective(Shocksanddevice102 record, Shocksanddevice102Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("shocksanddevice102.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    public int updateByExample(Shocksanddevice102 record, Shocksanddevice102Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("shocksanddevice102.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table shocksanddevice102
     *
     * @abatorgenerated Tue Mar 01 11:46:53 CST 2016
     */
    private static class UpdateByExampleParms extends Shocksanddevice102Example {
        private Object record;

        public UpdateByExampleParms(Object record, Shocksanddevice102Example example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}