package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Transferdevice101;
import com.changan.plcinterface.model.Transferdevice101Example;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Transferdevice101DAOImpl extends SqlMapClientDaoSupport implements Transferdevice101DAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice101
     *
     * @abatorgenerated Sat Mar 05 19:18:56 CST 2016
     */
    public Transferdevice101DAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice101
     *
     * @abatorgenerated Sat Mar 05 19:18:56 CST 2016
     */
    public void insert(Transferdevice101 record) {
        getSqlMapClientTemplate().insert("transferdevice101.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice101
     *
     * @abatorgenerated Sat Mar 05 19:18:56 CST 2016
     */
    public List selectByExample(Transferdevice101Example example) {
        List list = getSqlMapClientTemplate().queryForList("transferdevice101.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice101
     *
     * @abatorgenerated Sat Mar 05 19:18:56 CST 2016
     */
    public int deleteByExample(Transferdevice101Example example) {
        int rows = getSqlMapClientTemplate().delete("transferdevice101.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice101
     *
     * @abatorgenerated Sat Mar 05 19:18:56 CST 2016
     */
    public int countByExample(Transferdevice101Example example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("transferdevice101.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice101
     *
     * @abatorgenerated Sat Mar 05 19:18:56 CST 2016
     */
    public int updateByExampleSelective(Transferdevice101 record, Transferdevice101Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("transferdevice101.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice101
     *
     * @abatorgenerated Sat Mar 05 19:18:56 CST 2016
     */
    public int updateByExample(Transferdevice101 record, Transferdevice101Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("transferdevice101.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table transferdevice101
     *
     * @abatorgenerated Sat Mar 05 19:18:56 CST 2016
     */
    private static class UpdateByExampleParms extends Transferdevice101Example {
        private Object record;

        public UpdateByExampleParms(Object record, Transferdevice101Example example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}