package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Transferdevice;
import com.changan.plcinterface.model.TransferdeviceExample;
import com.changan.plcinterface.model.TransferdeviceKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TransferdeviceDAOImpl extends SqlMapClientDaoSupport implements TransferdeviceDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public TransferdeviceDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public void insert(Transferdevice record) {
        getSqlMapClientTemplate().insert("transferdevice.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public int updateByPrimaryKey(Transferdevice record) {
        int rows = getSqlMapClientTemplate().update("transferdevice.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public int updateByPrimaryKeySelective(Transferdevice record) {
        int rows = getSqlMapClientTemplate().update("transferdevice.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public List selectByExample(TransferdeviceExample example) {
        List list = getSqlMapClientTemplate().queryForList("transferdevice.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public List selectByExamplePage(TransferdeviceExample example) {
        List list = getSqlMapClientTemplate().queryForList("transferdevice.abatorgenerated_selectByExamplePage", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public Transferdevice selectByPrimaryKey(TransferdeviceKey key) {
        Transferdevice record = (Transferdevice) getSqlMapClientTemplate().queryForObject("transferdevice.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public int deleteByExample(TransferdeviceExample example) {
        int rows = getSqlMapClientTemplate().delete("transferdevice.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public int deleteByPrimaryKey(TransferdeviceKey key) {
        int rows = getSqlMapClientTemplate().delete("transferdevice.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public int countByExample(TransferdeviceExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("transferdevice.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public int updateByExampleSelective(Transferdevice record, TransferdeviceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("transferdevice.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    public int updateByExample(Transferdevice record, TransferdeviceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("transferdevice.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    private static class UpdateByExampleParms extends TransferdeviceExample {
        private Object record;

        public UpdateByExampleParms(Object record, TransferdeviceExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}