package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Transferdevice;
import com.changan.plcinterface.model.TransferdeviceExample;
import com.changan.plcinterface.model.TransferdeviceKey;
import java.util.List;

public interface TransferdeviceDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    void insert(Transferdevice record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    int updateByPrimaryKey(Transferdevice record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    int updateByPrimaryKeySelective(Transferdevice record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    List selectByExample(TransferdeviceExample example);

    List selectByExamplePage(TransferdeviceExample example);
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    Transferdevice selectByPrimaryKey(TransferdeviceKey key);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    int deleteByExample(TransferdeviceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    int deleteByPrimaryKey(TransferdeviceKey key);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    int countByExample(TransferdeviceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    int updateByExampleSelective(Transferdevice record, TransferdeviceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice
     *
     * @abatorgenerated Sun May 08 19:15:06 CST 2016
     */
    int updateByExample(Transferdevice record, TransferdeviceExample example);
}