package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Transferdevice101;
import com.changan.plcinterface.model.Transferdevice101Example;
import java.util.List;

public interface Transferdevice101DAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice101
     *
     * @abatorgenerated Sat Mar 05 19:18:56 CST 2016
     */
    void insert(Transferdevice101 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice101
     *
     * @abatorgenerated Sat Mar 05 19:18:56 CST 2016
     */
    List selectByExample(Transferdevice101Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice101
     *
     * @abatorgenerated Sat Mar 05 19:18:56 CST 2016
     */
    int deleteByExample(Transferdevice101Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice101
     *
     * @abatorgenerated Sat Mar 05 19:18:56 CST 2016
     */
    int countByExample(Transferdevice101Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice101
     *
     * @abatorgenerated Sat Mar 05 19:18:56 CST 2016
     */
    int updateByExampleSelective(Transferdevice101 record, Transferdevice101Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table transferdevice101
     *
     * @abatorgenerated Sat Mar 05 19:18:56 CST 2016
     */
    int updateByExample(Transferdevice101 record, Transferdevice101Example example);
}