package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Wprecordinformation;
import com.changan.plcinterface.model.WprecordinformationExample;
import com.changan.plcinterface.model.WprecordinformationKey;
import java.util.List;

public interface WprecordinformationDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    void insert(Wprecordinformation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    int updateByPrimaryKey(Wprecordinformation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    int updateByPrimaryKeySelective(Wprecordinformation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    List selectByExample(WprecordinformationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    Wprecordinformation selectByPrimaryKey(WprecordinformationKey key);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    int deleteByExample(WprecordinformationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    int deleteByPrimaryKey(WprecordinformationKey key);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    int countByExample(WprecordinformationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    int updateByExampleSelective(Wprecordinformation record, WprecordinformationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    int updateByExample(Wprecordinformation record, WprecordinformationExample example);
}