package com.changan.plcinterface.dao;

import com.changan.plcinterface.model.Wprecordinformation;
import com.changan.plcinterface.model.WprecordinformationExample;
import com.changan.plcinterface.model.WprecordinformationKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class WprecordinformationDAOImpl extends SqlMapClientDaoSupport implements WprecordinformationDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    public WprecordinformationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    public void insert(Wprecordinformation record) {
        getSqlMapClientTemplate().insert("wprecordinformation.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    public int updateByPrimaryKey(Wprecordinformation record) {
        int rows = getSqlMapClientTemplate().update("wprecordinformation.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    public int updateByPrimaryKeySelective(Wprecordinformation record) {
        int rows = getSqlMapClientTemplate().update("wprecordinformation.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    public List selectByExample(WprecordinformationExample example) {
        List list = getSqlMapClientTemplate().queryForList("wprecordinformation.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    public Wprecordinformation selectByPrimaryKey(WprecordinformationKey key) {
        Wprecordinformation record = (Wprecordinformation) getSqlMapClientTemplate().queryForObject("wprecordinformation.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    public int deleteByExample(WprecordinformationExample example) {
        int rows = getSqlMapClientTemplate().delete("wprecordinformation.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    public int deleteByPrimaryKey(WprecordinformationKey key) {
        int rows = getSqlMapClientTemplate().delete("wprecordinformation.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    public int countByExample(WprecordinformationExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("wprecordinformation.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    public int updateByExampleSelective(Wprecordinformation record, WprecordinformationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("wprecordinformation.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    public int updateByExample(Wprecordinformation record, WprecordinformationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("wprecordinformation.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table wprecordinformation
     *
     * @abatorgenerated Tue Dec 29 15:50:43 CST 2015
     */
    private static class UpdateByExampleParms extends WprecordinformationExample {
        private Object record;

        public UpdateByExampleParms(Object record, WprecordinformationExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}