package com.changan.mesinterface.dao;

import com.changan.mesinterface.model.Degasserprocdata;
import com.changan.mesinterface.model.DegasserprocdataExample;
import java.util.List;

public interface DegasserprocdataDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    void insert(Degasserprocdata record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    int updateByPrimaryKey(Degasserprocdata record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    int updateByPrimaryKeySelective(Degasserprocdata record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    List selectByExample(DegasserprocdataExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    Degasserprocdata selectByPrimaryKey(Integer fId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    int deleteByExample(DegasserprocdataExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    int deleteByPrimaryKey(Integer fId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    int countByExample(DegasserprocdataExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    int updateByExampleSelective(Degasserprocdata record, DegasserprocdataExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    int updateByExample(Degasserprocdata record, DegasserprocdataExample example);
}