package com.changan.mesinterface.dao;

import com.changan.mesinterface.model.Degasserdensitydata;
import com.changan.mesinterface.model.DegasserdensitydataExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DegasserdensitydataDAOImpl extends SqlMapClientDaoSupport implements DegasserdensitydataDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public DegasserdensitydataDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public void insert(Degasserdensitydata record) {
        getSqlMapClientTemplate().insert("degasserdensitydata.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public int updateByPrimaryKey(Degasserdensitydata record) {
        int rows = getSqlMapClientTemplate().update("degasserdensitydata.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public int updateByPrimaryKeySelective(Degasserdensitydata record) {
        int rows = getSqlMapClientTemplate().update("degasserdensitydata.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public List selectByExample(DegasserdensitydataExample example) {
        List list = getSqlMapClientTemplate().queryForList("degasserdensitydata.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public Degasserdensitydata selectByPrimaryKey(Integer fId) {
        Degasserdensitydata key = new Degasserdensitydata();
        key.setfId(fId);
        Degasserdensitydata record = (Degasserdensitydata) getSqlMapClientTemplate().queryForObject("degasserdensitydata.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public int deleteByExample(DegasserdensitydataExample example) {
        int rows = getSqlMapClientTemplate().delete("degasserdensitydata.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public int deleteByPrimaryKey(Integer fId) {
        Degasserdensitydata key = new Degasserdensitydata();
        key.setfId(fId);
        int rows = getSqlMapClientTemplate().delete("degasserdensitydata.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public int countByExample(DegasserdensitydataExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("degasserdensitydata.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public int updateByExampleSelective(Degasserdensitydata record, DegasserdensitydataExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("degasserdensitydata.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    public int updateByExample(Degasserdensitydata record, DegasserdensitydataExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("degasserdensitydata.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table degasserdensitydata
     *
     * @abatorgenerated Thu Dec 17 20:09:51 CST 2020
     */
    private static class UpdateByExampleParms extends DegasserdensitydataExample {
        private Object record;

        public UpdateByExampleParms(Object record, DegasserdensitydataExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}