package com.changan.mesinterface.dao;

import com.changan.mesinterface.model.Degasserprocdata;
import com.changan.mesinterface.model.DegasserprocdataExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DegasserprocdataDAOImpl extends SqlMapClientDaoSupport implements DegasserprocdataDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public DegasserprocdataDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public void insert(Degasserprocdata record) {
        getSqlMapClientTemplate().insert("degasserprocdata.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public int updateByPrimaryKey(Degasserprocdata record) {
        int rows = getSqlMapClientTemplate().update("degasserprocdata.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public int updateByPrimaryKeySelective(Degasserprocdata record) {
        int rows = getSqlMapClientTemplate().update("degasserprocdata.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public List selectByExample(DegasserprocdataExample example) {
        List list = getSqlMapClientTemplate().queryForList("degasserprocdata.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public Degasserprocdata selectByPrimaryKey(Integer fId) {
        Degasserprocdata key = new Degasserprocdata();
        key.setfId(fId);
        Degasserprocdata record = (Degasserprocdata) getSqlMapClientTemplate().queryForObject("degasserprocdata.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public int deleteByExample(DegasserprocdataExample example) {
        int rows = getSqlMapClientTemplate().delete("degasserprocdata.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public int deleteByPrimaryKey(Integer fId) {
        Degasserprocdata key = new Degasserprocdata();
        key.setfId(fId);
        int rows = getSqlMapClientTemplate().delete("degasserprocdata.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public int countByExample(DegasserprocdataExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("degasserprocdata.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public int updateByExampleSelective(Degasserprocdata record, DegasserprocdataExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("degasserprocdata.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    public int updateByExample(Degasserprocdata record, DegasserprocdataExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("degasserprocdata.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table degasserprocdata
     *
     * @abatorgenerated Thu Dec 17 19:59:43 CST 2020
     */
    private static class UpdateByExampleParms extends DegasserprocdataExample {
        private Object record;

        public UpdateByExampleParms(Object record, DegasserprocdataExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}